### ISSUE TITLE
Argument values are always lowercase

### ISSUE THREAD

**Issue by Teagan42** [gsscoder/commandline#106]
When running an application with a parser using the current cultureinfo (en-US in my case) or using the Default parser, all string values are being converted to lower case - as some of the parameters are search patterns, case is important.

Am I missing something or is this a bug?

library version: 1.9.71.2

**Comment by gsscoder** [comment]
Both versions accept this kind of customization via `ParserSettings`.

So if there's nothing more to ask, I close this issue. If I'm wrong feel free to re-open.

Giacomo :smile:
