### ISSUE TITLE
Check for multiple options attributes with same short letter

### ISSUE THREAD

**Issue by ErikApption** [gsscoder/commandline#112]
Currently if you specify option attributes and you use twice the same short option (as char) the parser will fail without details (parser.parse will return false). I would suggest raising an exception for this case.

**Comment by gsscoder** [comment]
I don't know if you're talking of 1.9.x or 2.0.x, @ErikApption, but @eric-newton is right. Currently 2.0.x contains a collection of `Error` in `ParserResult<T>.Errors`.

I'll write a unit test to bring this issue to light.

Thank you.

**Comment by gsscoder** [comment]
Fixed.
