### ISSUE TITLE
Question about MutuallyExclusive option.

### ISSUE THREAD

**Issue by mmajcica** [gsscoder/commandline#113]
Hi all,

I do want to have two  mutually exclusive options. It means if -i is selected, -u can't be selected.

This is the code I came up with.

```csharp
public class Options
    {
        [Option('i', "install", MutuallyExclusiveSet = "install", HelpText = "Choose install to install.")]
        public bool Install { get; set; }

        [Option('u', "uninstall", MutuallyExclusiveSet = "uninstall", HelpText = "Choose uninstall to uninstall.")]
        public bool Uninstall { get; set; }
}

static void Main(string[] args)
        {
            var options = new Options();

            Parser parser = new Parser(new ParserSettings { MutuallyExclusive = true });

            if (parser.ParseArguments(args, options))
            {
                if (options.Install) Console.WriteLine("Install option is chosen.");

                if (options.Uninstall) Console.WriteLine("Uninstall option is chosen.");

                Console.WriteLine("No option is chosen.");
            }
            else
            {
                Console.WriteLine("Options parsed with error.");
            }
        }
```
Unfortunately if both are selected, the ParseArguments returns true. Is this the expected behavior and if so how to handle a situation like this?

Thanks

**Comment by galmok** [comment]
I have tried to use this MutuallyExclusiveSet both according to how the documentation says and how it is described in this thread, but regardless of what I do, when I specify both options, no error is given.

        [Option('l', "language", MutuallyExclusiveSet = "a", Required = false, HelpText = "...")]
        public string Language { get; set; }

        [Option('d', "directory", MutuallyExclusiveSet = "a", Required = false, HelpText = "...")]
        public string Path { get; set; }

I have tried setting both to "a" and first to "a" and second to "b", but I get no parsing errors when I specify both options.

Is this option broken? I am using 1.9.71.

**Comment by gsscoder** [comment]
@agilbert201 is important to distinguish maturity between latest stable (1.9.* on its branch) and 2.0 pre-release. The last (that live on master branch) is an attempt to modernize the API from the exterior (making it more easy) and more robust, from the interior (using FP techniques) taking advantage of lesson learned in the past. In this fashion could be normal that something in border cases could behave weird (this is why I haven't changed the version number and also the definition that's still called **pre-release**.

**Comment by gsscoder** [comment]
@galmok no problem. Thanks for using the library.
Have a nice day.

**Comment by gsscoder** [comment]
@agilbert201 and @mmajcica, are you agree to close this issue?

**Comment by gsscoder** [comment]
http://stackoverflow.com/questions/10639320/command-line-parser-with-mutually-exclusive-required-parameters
