### ISSUE TITLE
How are unbound values parsed and returned to user

### ISSUE THREAD

**Issue by EliSchleifer** [gsscoder/commandline#117]
I saw in the wiki support for unbound values but it is not clear how those are actually returned from the Parse call.Any insights would be greatly appreciated.

**Comment by gsscoder** [comment]
Actually how 2.0.x parser is explained in appropriate [wiki section](https://github.com/gsscoder/commandline/wiki/Latest-Version).

Various things are changed in code and documentation, so I leave this issue open for further question. (But please check docs before).

**Comment by gsscoder** [comment]
Also after closing issue #162, I think this issue can be safely closed.
Thanks everyone for being there! :+1:
