### ISSUE TITLE
Command Line Parser Library but in single file instead of dll

### ISSUE THREAD

**Issue by cchitsiang** [gsscoder/commandline#121]
Similar to nDesk.Options. It provides DLL binaries and also single C# class file to import to the console app project.

Hope there is something similar to commandline

**Comment by gsscoder** [comment]
@cchitsiang,
is easy to embed also as multi file.
- Copy src/CommandLine to your/tree/CommandLine
- Delete your/tree/CommandLine/Properties folder
- Include the whole sub-tree with Visual Studio (show all files -> include in project)

And you're done!

_I've done it in a lot of commercial products where I had to ship only 1 exe and nothing more._

@nemec, thanks for comments.
@cchitsiang , thanks for being there! :+1:
