### ISSUE TITLE
ValueAttribute does not show up when Help is Auto-built.

### ISSUE THREAD

**Issue by prasannavl** [gsscoder/commandline#125]
ValueOptions should ideally have the HelpText, and an option name so that they may be displayed in the HelpText.

**Comment by gsscoder** [comment]
Yes, @prasannavl, you're right. I'm evaluating doing this ASAP. As you see a specific issue address this problem.

Thank you for being there.

**Comment by gsscoder** [comment]
Various issues about that, @prasannavl, all solved by #162!

Check it out!
