### ISSUE TITLE
Problem with unit testing

### ISSUE THREAD

**Issue by hiramegl** [gsscoder/commandline#129]
Hi, I've included CommandLineParser in a solution and started writing unit tests. I have strange problems with the ParseArguments method.

I wrote 4 tests (they have exacly the same code), the problem is that the first one executes correctly and the rest throw an exception:
---------------------------------
Result Message:	
Test method MyAppTest.MyAppBehaviour.ShouldDisplayHelpWhenNoArgumentsDefined2 threw exception: 
System.ObjectDisposedException: Cannot write to a closed TextWriter.
Result StackTrace:	
at System.IO.__Error.WriterClosed()
   at System.IO.StringWriter.Write(String value)
   at Microsoft.VisualStudio.TestPlatform.MSTestFramework.ThreadSafeStringWriter.Write(String value)
   at System.IO.TextWriter.SyncTextWriter.Write(String value)
   at CommandLine.Parser.DoParseArguments(String[] args, Object options)
   at CommandLine.Parser.ParseArguments(String[] args, Object options)
   at MyApp.MyApp.ParseArguments(String[] args)

-----------
My app invokes ParseArguments like this:

public class MyApp
 {
      Options options = new Options;
....
        private void ParseArguments(string [] args)
        {
            if (CommandLine.Parser.Default.ParseArguments(args, options) == false)
            {
                if (args.Length > 0 && args[0] != "--help")
                    Console.WriteLine("error");
                else
                    showHelp = true;
            }
        }
}

Any idea what can I change? Like I said this code works in the first test method but not in the rest (all of them have the same code, and all of them initialize a MyApp object)

Thanks for your help in advance!

**Comment by samneely** [comment]
Are there any plans to release the latest version on GitHub via NuGet?

**Comment by nemec** [comment]
The author abandoned this library a while ago. There is a [maintained fork](https://github.com/cosmo0/commandline) available but I don't think it's been published to NuGet yet.

**Comment by cosmo0** [comment]
It is: https://www.nuget.org/packages/CommandLineParser19/ and https://www.nuget.org/packages/CommandLineParser20/

**Comment by gsscoder** [comment]
2.0 is now quite usable, even if still in alpha. Latest commit (@ the moment of writing) is aligned with NuGet.
I think I can close this issue.
Please post back if needed! Project will continue to stay...
