### ISSUE TITLE
Please add missing license to repo

### ISSUE THREAD

**Issue by danielmarbach** [gsscoder/commandline#130]
https://commandline.codeplex.com/license

**Comment by goodmorninggoaway** [comment]
Please the license to this repo

**Comment by gsscoder** [comment]
The license is present on CodePlex License page and here on doc/LICENSE. The same, a MIT license.

Or do you mean other thing?

**Comment by goodmorninggoaway** [comment]
I see that now. I was looking for it in the top level. Thank you.

**Comment by gsscoder** [comment]
You're welcome!

Regards.

Il mercoledì 3 giugno 2015, Marque Davis <notifications@github.com> ha
scritto:
