### ISSUE TITLE
Using verbs, can the caller pass no arguments at all?

### ISSUE THREAD

**Issue by JMerrill** [gsscoder/commandline#137]
I want to have the power of verbs, but allow the caller to pass nothing on the command line. I had hoped to do that by handling a null or empty verb, and doing whatever the default thing is.

But before the verb gets collected by the onVerbCommand delegate, the library has already displayed the list of commands that are available. I had hoped that it would only show the commands when "help" was passed as the command line.

Do I have to test for args to be empty before calling the parser? That would be easy, but it the code structure would be completely different...

Thank you.

**Comment by mizipzor** [comment]
Seems like a solution was found and this has been inactive for nine months, closing. :)

**Comment by gsscoder** [comment]
@mizipzor, you're right, well done...
