### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by fireundubh** [gsscoder/commandline#140]
I installed Command Line Parser Library via NuGet, created an options class, and invoked the parsing method per the QuickStart guide. When I compile and run the program, I get this error:

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'CommandLine, Version=1.9.71.2, Culture=neutral, PublicKeyToken=de6f01bd326f8c32' or one of its dependencies. The system cannot find the file specified.
   at md5gen.Program.Main(String[] args)

I uninstalled the NuGet package, added the CommandLine project from Codeplex to my solution, and added CommandLine as a reference. When I compile and run the program, I get the same error.

Why is the program throwing this error? The package is installed, or the reference is there, and the project is there. Why can't the system see what's clearly there?

**Comment by gsscoder** [comment]
OK, we can close, I guess.
@fireundubh, thanks for using this library.
@cosmo0, @eric-newton, thanks for supporting new users.
