### ISSUE TITLE
Two same numbers in parameters result in no "value" error

### ISSUE THREAD

**Issue by teamalpha5441** [gsscoder/commandline#141]
When I invoke my client program with "./Client.exe edit -i 2 -r 2", it says that -r doesn't have a value. Error also occurs for any other numbers, as long as they are the same for -i and -r.
"Option 'rating, r' has no value."

See my client code here:
https://github.com/teamalpha5441/SharpBooru/tree/dd4d61581bd85351027f1e0769ba6c9c8236e820/Client/Options.cs
https://github.com/teamalpha5441/SharpBooru/tree/dd4d61581bd85351027f1e0769ba6c9c8236e820/Client/Program.cs

**Comment by torokze** [comment]
The problem exists in the CommandLine\Core\Tokenizer.cs
The 'tokens.Except(unkTokens)' removes the duplicated token values (Value tagged) from the tokens container even when the unkTokens is empty.

**Comment by gsscoder** [comment]
This still persists with latest fixes? @teamalpha5441 @torokze

**Comment by torokze** [comment]
Sorry gsscoder, I don't know, haven't used commandline since (I had other works to do).

**Comment by gsscoder** [comment]
@torokze, no problem. The project has been halted for a while, so some reply came after months... My fault. Regards.
