### ISSUE TITLE
NullReferenceException if no verb is specified

### ISSUE THREAD

**Issue by thomaslevesque** [gsscoder/commandline#142]
I'm trying to use the "verb commands" feature, but when I don't pass any argument on the command line, the `ParseArguments` method throws a `NullReferenceException` with the following stack trace:

<pre>
   at CommandLine.HelpVerbOptionAttribute.InvokeMethod(Object target, Pair`2 helpInfo, String verb, String& text)
   at CommandLine.Parser.DisplayHelpVerbText(Object options, Pair`2 helpInfo, String verb)
   at CommandLine.Parser.DoParseArgumentsVerbs(String[] args, Object options, Object& verbInstance)
   at CommandLine.Parser.ParseArguments(String[] args, Object options, Action`2 onVerbCommand)
   at NZip.Program.Main(String[] args) in d:\Docs\GitHub\NZip\NZip\Program.cs:line 18
</pre>

I'm using version 1.9.71.2

Here's my option class:

```csharp
    class Options
    {
        public Options()
        {
            CreateOptions = new CreateZipOptions();
        }

        [VerbOption("create", HelpText = "Create a new zip archive")]
        public CreateZipOptions CreateOptions { get; set; }
    }

    class CreateZipOptions
    {
        [ValueList(typeof(List<string>))]
        public IList<string> Items { get; set; }

        [Option('o', "OutputName", Required = true, HelpText = "Name of the output zip file")]
        public string OutputName { get; set; }
    }
```

And here's how I use it:

```csharp
        static void Main(string[] args)
        {
            var options = new Options();
            string verb = null;
            object verbOptions = null;
            Action<string, object> verbHandler = (v, o) =>
            {
                verb = v;
                verbOptions = o;
            };
            if (!Parser.Default.ParseArguments(args, options, verbHandler))
            {
                Environment.Exit(Parser.DefaultExitCodeFail);
            }
        }
```

**Comment by gsscoder** [comment]
@thomaslevesque,
similar issues were posted and fixed.

With **2.0.x-pre** there's absolutely no problem in using verb commands, with only **one verb**.
Just remember to use the variadic `ParseArguments(args, params types[]...)` overload and pass it `typeof(CreateOptions)`.

P.S.: _Thanks again to @cosmo0 for accepting PR in its fork during my absence..._

**Comment by amccool** [comment]
I just ran into this as well on 1.9.71.2.  Any chance we could get that PR into a stable nuget update?

**Comment by marcbarry** [comment]
+1
