### ISSUE TITLE
HelpText.AutoBuild throws unhelpful exceptions if certain assembly attributes are blank

### ISSUE THREAD

**Issue by JLRishe** [gsscoder/commandline#143]
I added the Command Line library to one of my programs today, and I found that when the program called `HelpText.AutoBuild()`, it threw a `TargetInvocationException` whose inner exception was an `ArgumentException` with the message `"programName"`.

After stepping into the method using Reflector, I found that the crux of where the errors occurs is here:

    HelpText text = new HelpText {
        Heading = (string) HeadingInfo.Default,
        Copyright = (string) CopyrightInfo.Default,
        AdditionalNewLineAfterOption = true,
        AddDashesToOption = !verbsIndex
    };

If the assembly's `AssemblyTitle` attribute is present but has a blank string value, then `HeadingInfo.Default` throws an exception at this line in the `HeadingInfo` contstructor:

    if (string.IsNullOrWhiteSpace("programName")) throw new ArgumentException("programName");

If the AssemblyCopyright attribute is present but blank, then the `HelpText.Copyright` `set` accessor throws an exception.

It seems that there is fallback logic for the case where these attributes are absent, but not for when they are blank. It would be nice if the fallback logic were used when they are blank, or if the library at least gave a helpful error message when they are.

**Comment by gsscoder** [comment]
When you use `AutoBuild` (if I'm not wrong the behaviour is similar in both stable and pre-rel), you're requesting an automatic help screen generation with a **Convention-Over-Configuration** pattern.

If you call `AutoBuild` Both attributes you quoted must be defined and if you define these, you've to declare a content string `<> string.Empty`.

E.g.: if you use `AutoBuild` and omit these attributes an exception is raised: **this is an intended behaviour**.

When not satisfied with this standard behaviour, `HelpText` could be configured in full freedom.

Thank you for your interest in this project!

**Comment by JLRishe** [comment]
I have no complaints about the requirements for using the `AutoBuild` feature. If those two attributes need to be non-blank, that's fine with me.

The issue I was raising was about how the error is reported because when I encountered this error I had to do quite a lot of digging to figure out what I was doing wrong. The error that's thrown when `AssemblyTitle` is blank is an `ArgumentException` for a constructor that I'm not actually calling, and when `AssemblyCopyright` is blank, the error is an `ArgumentNullException` for a `set` accessor that I'm not actually setting.  So my suggestion would be to make the error handling a bit more friendly.

**Comment by Mgamerz** [comment]
I had this same issue, but the only message I was given was "value". It took me several hours to figure out that you have to fill out all the assembly information or this AutoBuild does not work. It doesn't appear to be documented that these attributes are required. It would be helpful in the examples of using this method that these assembly attributes are required.
