### ISSUE TITLE
OptionList attribute only works if you specify a short-arg

### ISSUE THREAD

**Issue by Pyroka** [gsscoder/commandline#145]
If you specify an OptionList argument without a short-arg, it parses the list as a string not a list.

e.g. if your options is this:

``` c#
class Options
{
  [OptionList('t', "tags")]
  public IList<string> Tags { get; set; }
}
```

Running with the command-line `app --tags nodejs:sinatra:nancyfx:fubumvc` will produce the expected 4-item list.

But if you change your options to this:

``` c#
class Options
{
  [OptionList("tags")]
  public IList<string> Tags { get; set; }
}
```

Running with the same command-line will give you the string `nodejs:sinatra:nancyfx:fubumvc`

(This is version 1.9.71 grabbed from NuGet)

**Comment by gsscoder** [comment]
You mean with the second and:
```bash
$ app -t nodejs:sinatra:nancyfx:fubumvc
```
If yes, this is certainly a thing to fix. Thank you, @Pyroka.

Nowadays, 2.0.x-pre is quite _usable_ at least to be tested for our needs. Using such version (there's a pre-release also on NuGet now, but I suggest to compile from sources) you've to define you class as:
```csharp
{
  [Option('t', "tags", Separator=":")]
  public IEnumerable<string> Tags { get; set; }
}
``` 

Unit tests about this, make me suppose there 2.0.x-pre lacks this problem, if not please let me know.

Remember documentation link: https://github.com/gsscoder/commandline/wiki/Latest-Version.

**Comment by gsscoder** [comment]
OK, for **2.0** it works. So I can close the issue.
