### ISSUE TITLE
ValueAttribute is not a first class citizen

### ISSUE THREAD

**Issue by mbrenn** [gsscoder/commandline#146]
There are functions in OptionAttribute like HelpText and Required Parameter, which do not work with the ValueAttribute. 
Regarding the ValueAttribute as something like a first class citizen like the OptionAttribute would improve the use of unnamed arguments.

It is also relates to #125 and #117.

**Comment by gsscoder** [comment]
Issue #162 implemented right now addresses exactly this, @mbrenn, checkout master branch or download a NuGet _-Pre release_.

Thanks for being there! :+1:
