### ISSUE TITLE
Can't parse the argument has UTF8 chars

### ISSUE THREAD

**Issue by huoxudong125** [gsscoder/commandline#147]
When CommandLine.Parser.Default.ParseArguments(args, options) 
if args have '中文' the lib can't parse correctly.

**Comment by gsscoder** [comment]
Hi @huoxudong125,
sorry for replying so late... Anyway if you follow the project, you already know that work is now completely restarted.

Issue you reported can be true for both versions, but can I know if you use the stable or latest pre-release?

**Comment by gsscoder** [comment]
As you can see from InstanceBuilderTests::[Parse_utf8_string_correctly](https://github.com/gsscoder/commandline/blob/master/src/CommandLine.Tests/Unit/Core/InstanceBuilderTests.cs#L677) should not be a parser problem; at least not for **2.0.x-pre+**. 

Can I have more info about your test environment?
- Operating System (Type, Version)
- Terminal Application (Name, Version)

**Comment by gsscoder** [comment]
This is also in README.md samples, so I think the issue can be closed.
