### ISSUE TITLE
Example with error handling

### ISSUE THREAD

**Issue by nicolasr75** [gsscoder/commandline#156]
Can anyone provide a simple example on how to handle parsing errors with the current version (1.9.71)?
I have set up my Options class and am calling

    var options = new Options();

    if (CommandLine.Parser.Default.ParseArguments(args, options))
    {
        ....
    }
    else
    {
        //### how to get error information ???
    }

Or is this not the way it is supposed to work? Actually I would simply like to show the user which arguments he is missing.

**Comment by gsscoder** [comment]
Hi @nicolasr75,
the [wiki](https://github.com/gsscoder/commandline/wiki) is aligned to that version and only the section Latest Beta is about the master branch (2.0 pre-rel). Said that, help subsystem is not changed a lot...

As explained in [Display A Help Screen](https://github.com/gsscoder/commandline/wiki/Display-A-Help-Screen) is just a matter of adding a `GetUsage()` method capable of returning a `string` and properly marked as `[HelpOption]`. Its content will be printed to the output you specified in parser settings (depending on `ParseArguments()` overload); the default to `Console.Error` is general the best practice.

If you switch proper branch in GitHub, there's also demo apps and templates: https://github.com/gsscoder/commandline/tree/stable-1.9.71.2/src.
This is how I complete my `Options` class for automatic help handling:
```csharp
[ParserState]
public IParserState LastParserState { get; set; }

[HelpOption]
public string GetUsage() {
  return HelpText.AutoBuild(this, current => HelpText.DefaultParsingErrorsHandler(this, current));
}
```
In 2.0 pre-rel (under active development) all this is completely automatic (i.e.: nothing to write); but as I said is still a pre-release.

Coming back to your question, you don't need nothing in your `else` body, just exit or if you want a more synthetic code:
```csharp
if (parser.ParseArgumentsStrict(args, options, () => Environment.Exit(-2))) {
  // manage your instance here
}
```

_Just a last side note: this is more a question to post on Stackoverflow than an issue; so more people can take advantage from the reply._

**Comment by nicolasr75** [comment]
Thanks for the detailed reply! Sorry, I wasn't aware of the error handling description under 'Display a help screen' section.

**Comment by gsscoder** [comment]
Absolutely, no problem @nicolasr75; and please back if you've other questions. We're happy you use the library!

Have a nice day.
