### ISSUE TITLE
Nuget errors 

### ISSUE THREAD

**Issue by mizipzor** [gsscoder/commandline#167]
Getting the below errors when I try to build the solution. I have the most recent NuGet client installed, it seems the problem is the commited binary in .nuget. I also can't find where command (last error line) is executed, some build script? Is there a reason 

why the NuGet client is in the repository? Isn't it better to rely on the users locally installed one?

Edit: I should add that I can fix the errors by right clicking the *CommandLine.Tests* project then *Manage NuGet Packages...* and then clicking *Restore*. I only get the errors if I *Build solution* right after opening a fresh clone.

```
Error	23	The schema version of 'xunit' is incompatible with version 2.2.40207.9053 of NuGet. Please upgrade NuGet to the latest version from http://go.microsoft.com/fwlink/?LinkId=213942.	CommandLine.Tests
Error	24	The schema version of 'xunit.abstractions' is incompatible with version 2.2.40207.9053 of NuGet. Please upgrade NuGet to the latest version from http://go.microsoft.com/fwlink/?LinkId=213942.	CommandLine.Tests
Error	25	The schema version of 'xunit.assert' is incompatible with version 2.2.40207.9053 of NuGet. Please upgrade NuGet to the latest version from http://go.microsoft.com/fwlink/?LinkId=213942.	CommandLine.Tests
Error	26	The schema version of 'xunit.core' is incompatible with version 2.2.40207.9053 of NuGet. Please upgrade NuGet to the latest version from http://go.microsoft.com/fwlink/?LinkId=213942.	CommandLine.Tests
Error	27	The schema version of 'xunit.extensibility.core' is incompatible with version 2.2.40207.9053 of NuGet. Please upgrade NuGet to the latest version from http://go.microsoft.com/fwlink/?LinkId=213942.	CommandLine.Tests
Error	28	The schema version of 'xunit.extensions' is incompatible with version 2.2.40207.9053 of NuGet. Please upgrade NuGet to the latest version from http://go.microsoft.com/fwlink/?LinkId=213942.	CommandLine.Tests
Error	29	The command ""D:\dev\commandline\.nuget\NuGet.exe" install "D:\dev\commandline\src\CommandLine.Tests\packages.config" -source ""  -RequireConsent -o "D:\dev\commandline\packages"" exited with code 1.	CommandLine.Tests```

**Comment by gsscoder** [comment]
Hi @mizipzor,
yes you're right adding `.nuget` to source control was an oversight and was removed with last commit.

I think that this should solve also your build problems. If you fetch the very last sources, I've recently fixed `build.fsx` (it had problems with `test` task).

Unfortunately we can't run unit tests on Mono because xUnit console runners (recently upgraded to right version), currently work only on Windows. There's an (already open) issue on their GitHub repo, where I've posted my terminal output.

Please let me know, if this solved.

**Comment by mizipzor** [comment]
Exactly what I was looking for, thank you.

**Comment by gsscoder** [comment]
@mizipzor, you're welcome!

More things we fix, more rapidly I can promote **pre-release** to **alpha**.
