### ISSUE TITLE
Verb commands help text not displaying verb name or HelpText

### ISSUE THREAD

**Issue by mauricemeyer** [gsscoder/commandline#173]
An issue I just encountered with the help for Verb commands, e.g. the following definition for a `mv` verb

```c#
        [Verb("mv", HelpText = "Move a file to another location")]
        internal class MoveOptions
        {
            [Option('f', "force", HelpText="Overwrite existing files")]
            public bool Force { get; set; }

            [Option('l', "LoadRequest", HelpText = "generic help text")]
            public bool LoadRequest { get; set; }
        }
```
If I now pass *help mv* or *mv --help*, the according help page is displayed as the following

![help](https://cloud.githubusercontent.com/assets/7683567/8305109/13eaa6cc-19ac-11e5-8b26-79ea116c73aa.png)

Neither the verb command is displayed nor the HelpText associated to it. Is this behaviour intended, and if not could I request a fix?

Thanks!

**Comment by gsscoder** [comment]
If you want to display the help summary you don't have to specify any argument for implicit `help` verb:
```bash
$ app help
```
and for specific verb:
```bash
$ app help mv
```
This is an intended behaviour.

**Comment by mauricemeyer** [comment]
Ok, good to know, thanks!
Keep up the good work, it's a really great library.

**Comment by gsscoder** [comment]
Thank you, @mauricemeyer!
This wasn't possible with contributors help...

cc/ @mizipzor @nemec @gimmemoore
