### ISSUE TITLE
Allow DefaultValue = null

### ISSUE THREAD

**Issue by Sycobob** [gsscoder/commandline#175]
For a collection option, it would be useful to know whether the option was supplied or not. Thus, I propose allowing Option.DefaultValue to be set to null.

Ultimately, I'd like to be able to differentiate between

1. MyUtility <other options>
2. MyUtility <other options> --ToggleRefreshRate
3. MyUtility <other options> --ToggleRefreshRate 60 120

In 1, user has not specified the command, so do nothing.
In 2, user has specified the command, but no values, so use defaults (determined at runtime).
In 3, user has specified the command and a set of values, use specified values.

It makes sense for the value of the IEnumerable<int> property associated with ToggleRefreshRate  to be null, empty, and { 60, 120 } respectively, which is not currently possible.

Also necessary for this is the ability to specify a collection option with no values, as in case 2. Perhaps through Min = 0? (See #176)

**Comment by gsscoder** [comment]
If possible try to avoid giving ``null`` a meaning.

As explined in #176. A collection is automatically build as empty collection when receives no values. See the other issue.

**Comment by gsscoder** [comment]
I close the issue since discussion will better focused in one issue: #176.
