### ISSUE TITLE
Using Option.SetName disallows non-set Options

### ISSUE THREAD

**Issue by Sycobob** [gsscoder/commandline#177]
If any Option with a SetName is provided, a parsing error will result if any Option *without* a SetName is provided. e.g. with the options

    [Option('v', "Verbose")]
    public bool Verbose { get; set; }

    [Option('r', "ToggleRefresh", SetName = "Refresh")]
    public IEnumerable<int> ToggleRefreshRate { get; set; }

and the arguments `-v -r 60 120` results in errors:

    ERROR(S):
      Option 'Verbose, v' is defined along with an incompatible one.
      Option 'ToggleRefresh, r' is defined along with an incompatible one.

Presumably, sets should be exclusive with one another, but not exclusive with *non-set items*.

**Comment by gsscoder** [comment]
The problem here is that you've two options and two sets. The option without as set implicitly belongs to an empty set (say the ``""`` set). (Same thing when you define ten options without a set, all ten belong to ``""`` implicit empty set).

In this way one-option set result in being mutually exclusive by each other.

I hop I was clear... :smile: If this not helped, please ask again.

**Comment by Sycobob** [comment]
Yes, your explanation was clear. I suppose this becomes a matter of design then. It seems like the empty set should not act as a set.

For example, assume you have two sets: 'ftp' and 'web', where the options need to be exclusive. Now assume you have an option that is relevant in both cases, such as 'verbose'. In the current state, it is not possible to simultaneously support `MyUtility -v <ftp stuff>` and `MyUtility -v <web stuff>`. This seems like a very common use case.

**Comment by mizipzor** [comment]
I agree that it makes (more) sense to have any option not belonging to any set not be considered  by set constraint rules.

**Comment by gsscoder** [comment]
@Sycobob, @mizipzor, OK, this makes sense...!

I'll write a unit test to put in evidence this issue.

**Comment by gsscoder** [comment]
@Sycobob, @mizipzor, please check latest source.
This logic is now implemented.

P.S.: just to be scrupulous, I'll all add tests when `Required` attribute is involved.
