### ISSUE TITLE
More correct ParserResult<T> type

### ISSUE THREAD

**Issue by gsscoder** [gsscoder/commandline#180]
Sincerely, even if maybe _comfortable_ for some kind of usage, I see as discrepancy the possibility to gain access to `ParserResult<T>.Value` when `ParserResult<T>.Errors.Count() > 0`.

Obviously I don't want to raise exception in `Value` to protect this condition... This _design issue_ had a practical reason tied to help subsystem. `HelpText` queries the instance to read `T` attribute and in a verb scenario of `ParserResult<object>` if `typeof(T)` will return `System.Object` and the only way to get a proper `System.Type` instance is to query `...Value.GetType()`.

I'd like to define something similar to this **F#** code:
```fsharp
type ParserResult<'a> =
  | Parsed of 'a
  | NotParsed of seq<Error>
```

To simplify this change value will be present but hidden to library consumers. To be correct probably each verb overload should have a specific parser result but this will complicated and pollute the library with a lot of public types.

cc/ @mizipzor @nemec @gimmemoore

**Comment by gsscoder** [comment]
A simpler solution could be expose the internal `Maybe<T>` and define `Value` with it. This class as the same meaning of `FSharpOption<T>` (`option<'a>`) and probably future versions of C# will expose something like this directly in `System` namespace.

I don't like this solution: because `ParserResult<T>` should be a domain specific `Maybe` of command line parser library.

For verb we can define data structure similar to `Choice<'a,'b,..>` https://msdn.microsoft.com/en-us/library/ee353439.aspx... But it will be verbose. I don't know. But it's possible that defining something tied to library domain could be the most clean way of representing verb choice.

I'm sure only about one thing at the moment: this refactoring must be gradual...

**Comment by gsscoder** [comment]
```csharp
// concise, pseudo c#
abstract ParserResult<T> {
  internal T Value { ... };
}
class Parsed<T> : ParserResult<T>  { // Tag.Parsed
  public T Value { get { return base.Value; } }
}
class NotParsed<T> : ParserResult<T> [ // Tag.NotParsed
  public IEnumerable<Errors> { ... }
}
```

**Comment by gsscoder** [comment]
**verbs:**
```csharp
abstract ParserResult<T1, T2> {
}
class Parsed1Of2<T1> : ParserResult<T1, T2> {
 public T1 Value { ... }
}
class Parsed2Of1<T2> : ParserResult<T1, T2> {
 public T2 Value { ... }
}
```
Since we have till `ParserArguments<T1...T16>()`, we need other 14 boiler plate code like this... :(

**Comment by nemec** [comment]
You're right, with verbs it gets very unwieldy. I wonder if it would be a good idea to do some Expression magic:

    ParserResult<T> results = parser.ParseArguments([...]);
    ParserResult<VerbType> vResult = results.ForVerb(t => t.MyVerbProperty);

Or even a dictionary you can index by type, but that wouldn't work if two verbs share the same type.

**Comment by gsscoder** [comment]
@nemec, I think we should add gradually two thing:
- a ParserResult<T> like the discriminated union in the first post
- a ParserResult<T1, T2,... etc> like Microsoft.FSharp.Chore.Choiche<T1, T2, ...> (that is the correct functional way of representing such situation)

**Comment by gsscoder** [comment]
I'm working on it on a dev branch:
https://github.com/gsscoder/commandline/blob/presult180/src/CommandLine/ParserResult.cs

**Comment by gsscoder** [comment]
@nemec, the first refactoring is almost completed... Can you explain better your idea for verb scenario and `Expression` magic?

Something like this: https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Core/ReflectionExtensions.cs#L107 ?

**Comment by gsscoder** [comment]
I close the issue, we can open another one for verb scenario.

**Comment by gsscoder** [comment]
@nemec, have you seen latest helper for verbs? I think they are a good compromise for access data and keep code terse and clean...

**Comment by nemec** [comment]
Calling it 'Return' is a little vague to me and not really descriptive of *why* it should be used (such as performing an action based on parse result). If I understand correctly, it's basically a huge switch statement that executes a different delegate based on the parsed result? I think that will work.

You may want to add equivalent 'void' methods for the case when there is no natural return value:

    result.Return(
        verb => AppMain(),
        errors => DisplayHelp());

I haven't had a chance to run the new code, but how does it behave when no verb is provided? Such as how git has verbs like `pull` but also allows `git --version` without any verb. Would you have to provide your 'Options' class as `T1`? Otherwise, it looks like when you call `Return` looking for a verb when none was parsed (and there were no errors, since `--version` is valid, it will throw an `InvalidOperationException`.

Or am I totally off base?

**Comment by gsscoder** [comment]
The `Return` nomenclature is taken from the `Maybe` monad concept (generic [info](https://en.wikipedia.org/wiki/Monad_(functional_programming)).

Your sample is not correct since, you're invoking a `Func<TInput, TOutput>`: where you turn the instance of type `TInput` with values into something else and you do the same thing with errors too (`Func<IEnumerable<Error>>`).

```csharp
var newValue = result.Return(
  verb1 => ProcessVerb1AndReturnSomething(),
  verbX => ProcessVerbXAndReturnSomething(),
  errs => ProcessErrsAndReturnSomething());
```

Anyway I could be agree to evaluate a different more explicit semantic.

If you want go with `Action`s, you've specific helpers: `WithParsed` and `WithNotParsed` (to call chained).
