### ISSUE TITLE
Immutable Options doesn't work in verb scenario

### ISSUE THREAD

**Issue by Thilas** [gsscoder/commandline#184]
Hey,

For instance, if you try to use a class similar to FakeImmutableOptions (from the unit tests) in a verb scenario, you get a NullReferenceException. I tried to fix it but I'm not sure without rewriting a lot of code...
FYI, I found this issue while passing an empty Verb class to the parser.

Thanks,

Thomas

**Comment by gsscoder** [comment]
@Thilas,
thank you... You preceded me! This was the next tests I wanted to add to coverage.

Now I'm working on your PR, next I'll add tests for this issue.

Thanks! :+1:

**Comment by gsscoder** [comment]
If possible, I'd take advantage of your help to check if this is really fixed.

Thanks, again!

**Comment by Thilas** [comment]
@gsscoder ,
Tested successfully. I'll have a look to your fix to see how you did that :)
Thanks!

**Comment by gsscoder** [comment]
@Thilas, again thank you!

**Comment by sqc1999** [comment]
I am still getting the `NullReferenceException` with verbs and immutable types. Is there anyone can help?

**Comment by Thilas** [comment]
@sqc1999, how do you get this issue? Could you provide more information regarding your context? And could you put all that in a new issue since this one is already closed. Thanks!

**Comment by sqc1999** [comment]
@Thilas Oh, That's all my fault. I forgot to provide a constructor to initialize the read-only properties.

**Comment by Thilas** [comment]
@sqc1999, I'm glad to hear that :)
