### ISSUE TITLE
Unparse support

### ISSUE THREAD

**Issue by gsscoder** [gsscoder/commandline#186]
I want to be able to:
```csharp
class LsOptions {
  [Option('a')] public bool All { get; set; }
  [Option('h')] public bool HumanReadable { get; set; }
  [Option('l')] public bool LowerCase { get; set; }
  [Value(0)] public IEnumerable<string> Files { get; set; }
}

var opts = new LsOptions { All=true, HumanReadable=true, Files=new [] { "./doc", "./src" } };

var arguments = CommandLine.Parser.Default.Unparse(opts); //-> "-lh ./doc ./src"

Process.Start("ls", arguments)
```

w/ also other overloads, e.g. unparse to array, etc...

Opinions? cc/ @mizipzor @nemec @gimmemoore

**Comment by nemec** [comment]
Huh, that's a neat idea. You could even use this to quickly serialize calls across SSH to a "companion exe" on a remote machine that also uses CommandLine.

**Comment by gsscoder** [comment]
@nemec, yes, exactly...

**Comment by mizipzor** [comment]
I struggled to find a use for it, but yes a companion app somewhere else that could make use of arguments serialized in some way might be one. But still, wherever I would use ```Unparse``` couldnt I just use the ```arguments``` I sent the parser in the first place?

**Comment by gsscoder** [comment]
@mizipzor, scenarios may vary and people may find various way of using it. The interesting thing is that the library guarantees you that the command line formed will be **well formed**.

I'm also in favor of adding more level of abstraction, say the one reported in first post and this e.g.:
```csharp
var args = new Arguments().AddSwitch("x").AddString("longopt", "test").AddXXX(...).ToString();
``` 

To be honest is a feature I've seen in various similar library, employed by popular used open source projects; so I won't left behind!

**Comment by nemec** [comment]
One idea I just thought of: you could use it to generate examples for the Help subsystem using pure .Net code instead of building the argument string yourself.

**Comment by gsscoder** [comment]
@nemec, this is not clear... Can reformulate please?

**Comment by nemec** [comment]
Sure, say you have this Options class (and I'm making up an ExampleAttribute, which doesn't exist)

    public class Options
    {
        [Option('v', "verbose", HelpText="Verbosity level.")]
        public bool Verbose { get; set; }

        [Option('i', "input", HelpText="The input file.")]
        public string InputFile { get; set; }

        [Example(HelpText="Read from the input file verbosely."]
        public Options Example1 = new Options
        {
            Verbose = true,
            InputFile = "my downloads.txt"
        };
    }

Then when you call `$ app --help` you get:

    app 1.0.0.0
    Copyright c 2015
     -v, --verbose Verbosity level.
     -i, --input The input file.
     --help Display this help screen.

    Examples:
      $ app -v --input="my downloads.txt"
        Read from the input file verbosely.

It could correctly format things like quoting and let the user of the library define examples in the way that he/she wants them -- as .Net objects -- while the user of the application sees the examples as command line arguments.

**Comment by gsscoder** [comment]
@nemec, wow! :+1: This is cool.

I thought several times how to formalize this and finally I found a cool proposal, thank you.

Something like this will appear without doubt here! Thank you, very appreciated.

**Comment by gsscoder** [comment]
@nemec, for now I'll implement the basic feature. We can open a new issue for [Example] one.

**Comment by gsscoder** [comment]
Working on temporary dev branch `unparse186`.

**Comment by gsscoder** [comment]
Implemented in 2.0.101-alpha. Pushing to NuGet right now... :)

**Comment by gsscoder** [comment]
For reference: https://github.com/gsscoder/commandline/blob/master/src/CommandLine.Tests/Unit/UnParserExtensionsTests.cs.

**Comment by gsscoder** [comment]
@nemec, your excellent idea of `Example` attribute was moved to [this issue](https://github.com/gsscoder/commandline/issues/208). Thanks again
