### ISSUE TITLE
Example attribute for formatting usage with unparsing support

### ISSUE THREAD

**Issue by gsscoder** [gsscoder/commandline#208]
As describe [here](https://github.com/gsscoder/commandline/issues/186) by @nemec.

**Comment by gsscoder** [comment]
@nemec, instead of:
```csharp
[Example(HelpText = "Read from the input file verbosely."]
public Options Example1 = new Options
{
  Verbose = true,
   InputFile = "my downloads.txt"
};

[Example(HelpText = "Write to output."]
public Options Example2 = new Options
{
  OutputFile = "filtered.csv"
};
```
We can group everything with:
```csharp
[Usage]
public IEnumerable<Tuple<string, Options>> Examples // tuple of help string, sample instance
{
  yield return Tuple.Create("Read from the input file verbosely.", new Options { Verbose = true, InputFile = "my downloads.txt" });
  yield return Tuple.Create("Write to output.", new Options { OutputFile = "filtered.csv" });
}
```
What do you think?

**Comment by gsscoder** [comment]
@mizipzor, @gimmemoore, @Thilas, opinions?

**Comment by nemec** [comment]
I went back and forth between separate objects and a method like you have above and I like the option method too.

**Comment by gsscoder** [comment]
@nemec, we can define a custom tuple instead of generic one.
Like:
```csharp
[Usage]
public IEnumerable<Example<Options>> Examples // tuple of help string, sample instance
{
  yield return Example("Read from the input file verbosely.", new Options { Verbose = true, InputFile = "my downloads.txt" });
  yield return Example("Write to output.", new Options { OutputFile = "filtered.csv" });
}
```
Defined as:
```csharp
// define here mutable... but will be immutable
class Example<T> {
  public Example(string helpText, T sample) {
    HelpText = helpText; Sample = sample; 
  }
  public string HelpText { get; set; }
  public T Sample { get; set; }
}
```
This way is better further, I think.

**Comment by nemec** [comment]
I like that. It's more explicit about which item is the help text.

**Comment by Thilas** [comment]
I don't like Tuple but using an explicit class seems just fine to me, a little bit easier than using instances of "Options". Otherwise have you also thought about verbs?

**Comment by gsscoder** [comment]
@Thilas, yes. I'll use internally FormatCommandLine<T> that already works with verbs. If your example instance contains verb attribute than your sample command line will figure the verb.

I'm wondering if could be a cool thing, let the user group sample.

This is the first syntax comes to my mind:
```csharp
[Usage(Groups={{"grp1", "Samples about X"}, {"grp2", "Samples about Y"}})]
public IEnumerable<Example<Options>> Examples // tuple of help string, sample instance
{
  yield return Example("grp1", "Read from the input file verbosely.", new Options { Verbose = true, InputFile = "my downloads.txt" });
  yield return Example("grp2", "Write to output.", new Options { OutputFile = "filtered.csv" });
}
```
I've used dictionary syntax in `Groups` property of UsageAttribute.

Another cool thing could be supply an instance of `UnParserSettings` to customize command line appearance (at Example type level); also in form of sequence so you can provide more style of same sample. See [this](https://github.com/gsscoder/commandline/wiki/Latest-Version#unparsing).

The formatted command line will need to have also executable name. It can be derived with reflection, but an `Alias` can be useful if the app is provided by a special launch script (e.g.: in Linux/Mac to hide `mono` command`).

That's all folks! :)

**Comment by gsscoder** [comment]
Just another thing... For multilingual support we can provide a `string`-wrapper (like a dictionary) with CultureInfo codes. Or better a wrapper with that code and supply a list of it.

**Comment by gsscoder** [comment]
Forgot last comment, we must extend `SentenceBuilder` for that...

**Comment by gsscoder** [comment]
Work started in temp dev branch `usage208`.

**Comment by gsscoder** [comment]
First version (and maybe future) will not have grouping feature. Too verbose, not really necessary...

**Comment by gsscoder** [comment]
Done. I'll update docs as soon as possible.

**Comment by gsscoder** [comment]
https://github.com/gsscoder/commandline/wiki/Latest-Version#usage-attribute
