### ISSUE TITLE
Verbs and HelpText

### ISSUE THREAD

**Issue by Thilas** [gsscoder/commandline#217]
@gsscoder, while adding new unit tests on verbs, I found out that if you declare a verb without a `HelpText`, you get an `ArgumentNullException` (see https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Core/Verb.cs#L17).
Is this on purpose? I am asking because it is not the case on options or values.

**Comment by gsscoder** [comment]
@Thilas, maybe it's better provide a constructor that default to string.Empty. But in general I don't like an API where there's a meaning to setting something to `null`.

You're right, I can add this ctor right now...

**Comment by gsscoder** [comment]
Now I see, @Thilas, you're talking of Verb model not the attribute. Anyway. It's simple, solution is to give an empty default to avoid explicit  `HelpText == null`.

**Comment by gsscoder** [comment]
This is also coherent with https://github.com/gsscoder/commandline/blob/master/src/CommandLine/BaseAttribute.cs#L25.

**Comment by gsscoder** [comment]
I think issue can be closed, if you want to add comments, feel free to do it! :)

**Comment by Thilas** [comment]
@gsscoder, it sounds great! Thanks.

**Comment by gsscoder** [comment]
@Thilas :+1: Your contributions (issues, PRs, comments) are always really appreciated here!
