### ISSUE TITLE
Handling multiple occurrences of an option (--input foo --input bar)

### ISSUE THREAD

**Issue by asimonov-im** [gsscoder/commandline#229]
Do you have any plans to support multiple occurrences of an option, such that all arguments are saved, instead of only the last one? 

mybin --input foo --input bar => input = ["foo" "bar"]

You talked about this feature [here](https://commandline.codeplex.com/discussions/401966) but I'm not sure what the result of the discussion was.

**Comment by gsscoder** [comment]
@asimonov-im, sorry but that link you reported is quite old stuff. Updated discussion happens on GitHub also if time to time I'll update CodePlex home too.

You don't need a such verbose syntax.

If you want capture a sequence just attach your property to a sequence data type:
```csharp
class Options {
  [Option]
  public IEnumerable<string> Input { get; set; }
}
```
Here you can use also `Min\Max` to force a specific range minimum and maximum, avoiding it will capture all strings after `--input`.

Another option is the use of sepator:
```csharp
class Options {
  [Option(Separator('+')]
  public IEnumerable<string> Input { get; set; }
}

// allows:
// app --input foo+bar+baz+xyz
```

Hope it helped, if not back here and please ask again... :smile: !

**Comment by asimonov-im** [comment]
@gsscoder Thank you for the suggestions. Unfortunately I am unable to change the program interface, as a result of compatibility concerns. I am re-implementing an interface that already exists, and so I was trying to make it work with the parser library.

**Comment by gsscoder** [comment]
@asimonov-im, this is because someone else call your app and can't change how it's invoked? I guess...?

**Comment by gsscoder** [comment]
@asimonov-im, perfect :+1: ! I'm glad...

So if you don't need more help, please be kind to close the issue. :)

Have nice times.

**Comment by gsscoder** [comment]
@asimonov-im, for anything else, we're here! :)

**Comment by asimonov-im** [comment]
@gsscoder Much appreciated :)
