### ISSUE TITLE
Give no values to options, Occurs strange

### ISSUE THREAD

**Issue by yyypasserby** [gsscoder/commandline#236]
I used the stable version and when I

```
app -o
```

-o is mapped to a string, it ought to be an parse error but error occurs without error info when I use `DefaultParsingErrorsHandler`.

**Comment by gsscoder** [comment]
it's really difficult to help you, @yyypasserby, without further informations (try also to riformulate your question, sorry, but I didn't understand it..)

as said in various announcements, anyway, current beta is quite _stabilized_, so I esort you employ lib in the master branch or pop from NuGet the latest version (pre-release in gui, `Install-Package CommandLineParser -Pre` in VS package manager console)

thanks :+1: for choosing this project

**Comment by yyypasserby** [comment]
Thanks for your patience, I will try to use the beta version.

I define something like

```c#
Options['o', "output"]
public string Output { get; set; }
```

and use the `DefaultParsingErrorsHandler` to handle parsing error.

And when I call 

```cmd
app -o
```

I give no value to the option o.
What I expected is to print some errors, like 'violate format'. However, it only print some help infos, which means there are truly some error occurs, but why no error info?.

Do I use it right?

**Comment by nemec** [comment]
@gsscoder I think he's saying that when giving an option and leaving the value out (when it expects a value) doesn't give a descriptive error message.

**Comment by gsscoder** [comment]
@nemec, thanks for clarification. :)

I've created a console app with an `Options` with exactly the option you posted, here the full program:
```csharp
    class Options
    {
        [Option('o', "output")]
        public string Output { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Parser.Default.ParseArguments<Options>(args);
        }
    }
```

I call the parser doing nothing with with just to demonstrate that right error messag is printed:
```PowerShell
PS E:\...\bin\Debug> .\ConsoleApplication2.exe -o
ConsoleApplication2 1.0.0.0
Copyright ©  2015

ERROR(S):
  Option 'o, output' has no value.

  -o, --output

  --help          Display this help screen.

  --version       Display version information.
```

What's wrong? You gave no value and the error says that, here there's no **violation** of format, but a **lacking** of value.

This helped?

**Comment by yyypasserby** [comment]
The upgrade to latest version works for me. Thanks.

**Comment by gsscoder** [comment]
Peeeeeerfect! @yyypasserby, very happy! :)
