### ISSUE TITLE
CoreCLR Support

### ISSUE THREAD

**Issue by DerAlbertCom** [gsscoder/commandline#237]
Hi,

any plans for CoreCLR/ASP.NET 5 Console Application Support?

Need Help, or not interested?

**Comment by gsscoder** [comment]
@DerAlbertCom,
yes I'm interested and help will be appreciated. 

Starting from understanding if **CoreCLR** is a _general target_ or a target tied only to **ASP.NET 5**?

I'm also interested if prople call the library from web apps and if they do I'm really interested of what kind of use they do.
Or probably they create console apps use the lib and reference ASPNET runtime?

Please remember that every work of this kind will eventually start after stable is reached (as in #213).

:+1:

**Comment by DerAlbertCom** [comment]
Yes, it is a generell CoreCLR und CoreFX. Has nothing todo with ASP.NET. And the ASP.NET Console Application is not an ASP.NET Application. It is Console Application which runs on .NET Core. But there there is no right Place in "File New Project" now ;)

**Comment by DerAlbertCom** [comment]
I will not start before 2.0 release

**Comment by gsscoder** [comment]
Perfect, @DerAlbertCom, thansk for your interest and appreciated proposal of help! :)

So, it's perfect to coordinate ourselves after that release.

Thanks again.

**Comment by DerAlbertCom** [comment]
There is something out of the Box: http://jameschambers.com/2015/09/supporting-options-and-arguments-in-your-dnx-commands/ . so i don't know if i start porting ;/ will have to evaluate

**Comment by dazinator** [comment]
I know corefx are working on there own commandline parser at present:https://github.com/dotnet/corefxlab/blob/terrajobst/commandline/src/System.CommandLine/README.md#why-a-new-library

Would be good to see commandline support corefx / coreclr too though as its my favourite parser!

**Comment by gsscoder** [comment]
:paperclip: Please read: #250. Thanks for collaboration and patience! :sweat_smile:
Giacomo
_P.S.: valid only for me, if a main contrib. is available he's obviously free to support devs/users of the project._

**Comment by jeremymeng** [comment]
Hi, one of our customers has the need of a CoreClr port.  So we have been working on it.  I will submit a PR.  Please provide feedback!

**Comment by gsscoder** [comment]
@jeremymeng, thanks for your PR! :+1:
As said, after **2.0** will be promoted **STABLE**, I'll work on it.

Please be patient, but my time resources are limited in this period.

Thanks you, again!

**Comment by oocx** [comment]
CommandLineParser works for me in a .NET Core project, except for a minor bug. It shows a wrong version and copyright:

> ACME.Console.cmd
CommandLine 2.0.275-beta
Copyright (c) 2005 - 2015 Giacomo Stelluti Scala
(...)

The same code built for desktop clr has this output:
> acme.exe
Oocx.ACME 1.0.0.0
Copyright ©  2015

**Comment by jtattermusch** [comment]
I saw that most of the work has been done in dotnet-core branch. Is there an ETA for publishing a nuget that supports netstandard1.3?

**Comment by AlexanderButs** [comment]
Any news, guys, after .NET Core RTM release?

BTW, great library! Thanks.

**Comment by nemec** [comment]
Good news y'all, I've merged the `dotnet-core` branch into `master`. @jtattermusch I'm still pretty new to Core but it targets `netstandard1.5

**Comment by jtattermusch** [comment]
@nemec  thanks for merging the `dotnet-core` branch. To make the netstandard1.X support really usable though, a new version of nuget needs to be uploaded (to be created with the `dotnet pack` command). Are you planning to upload a new version of the nuget?

(In the meantime, I might upload an interim nuget package under a different name so I can start using it ASAP).

Ad netstandard1.5:  1.5 works fine for me, but I'd expect that 1.3 (or even lower) should be sufficient. At some point, if there is some effort to look into supporting something lower than 1.5, that could really  help expanding the CoreCLR user base.
