### ISSUE TITLE
GUID is not working for input parameter

### ISSUE THREAD

**Issue by pvmraghunandan** [gsscoder/commandline#241]
When trying to parse string variable that has value as GUID, parsing is failing. The version is : 1.9.71.2. Any alternative of parsing GUID?

**Comment by gsscoder** [comment]
@pvmraghunandan, can you please do a test with 2.0.*x (is quite stable and very near to be promoted to that status officially)?

**Comment by gsscoder** [comment]
@pvmraghunandan, I've done some research and no version will parse a Guid becuase it contains control characters `-` (single dash -> used by the parser to specificy **short options** or **short options group**).

I can suggest you to do the above o something similar.
1. Define an option class that will accept the guid in a temporary target property:
```csharp
class Options {
  [Option("transaction")]
  public string StringTransactionId { get; set; }

 public Guid TransactionId { get; set; }
}
```
2. Supply Guid using a different separation character and underscore (`_`) for example:
```bash
$ yourapp --transaction=05c7845a_a31c_4801_a615_0bfa4b625bef
```
3. After successful parsing rebuild the real value:
```csharp
var txId = new Guid(options.StringTransactionId);
options.TransactionId = txId;
```

If this helped, please close again the issue...! :)

**Comment by pvmraghunandan** [comment]
GUID is part of our input scripts. The problem of replacing is deployment team should aware and treat it as different which will complicate the process. I had given a try by using type as string instead of GUID. Seems like its working. I will do some test and postback

**Comment by gsscoder** [comment]
@pvmraghunandan, sorry **ERRATE CORRIGE**:
as this test demonstrates: https://github.com/gsscoder/commandline/blob/master/tests/CommandLine.Tests/Unit/Core/InstanceBuilderTests.cs#L917 there's no problem (at least with 2.0.x*) parsing a GUID o strings with in middle/end dashes (when '-' / '--' are not in the beginning of the string).

So maybe a problem in loading the parsed GUID in the targed property defined as System.Guid.

I'll edit first post, with a temporary solution, but I'll try to fix this issue.

**Comment by gsscoder** [comment]
As shown in test https://github.com/gsscoder/commandline/blob/master/tests/CommandLine.Tests/Unit/Core/InstanceBuilderTests.cs#L935 is now possible parse GUID to System.Guid properties.

Please test (obviously with version 2.0.273-beta -> also on NuGet) and close the issue if everything is ok.

**Comment by nemec** [comment]
I'm going to go ahead and close this issue unless we hear further from @pvmraghunandan
