### ISSUE TITLE
= not supported with short name?

### ISSUE THREAD

**Issue by asherber** [gsscoder/commandline#243]
Using 1.9.71.

Given this:
```
class Options
{
    [Option('f')]
    public int Foo { get; set; }
}
```
I can pass in `--foo=6`, but `-f=6` doesn't work. (`-f 6` is fine.) Is this intentional?

**Comment by gsscoder** [comment]
@asherber, exactly, it's about being `getopt()` *nix spec. compliance.

You can also: `-f6` and if have `x` and `y` valid short boolean options: `-xyf6` and `-xyf 6` are too valid.

**Comment by asherber** [comment]
Ah, got it, thanks.

**Comment by gsscoder** [comment]
My pleasure! :smile:
