### ISSUE TITLE
Auto-help has unsightly blank lines

### ISSUE THREAD

**Issue by rmunn** [gsscoder/commandline#244]
If I define AssemblyLicense and/or AssemblyUsage in my AssemblyInfo.cs file, the automatically-produced `--help` text has unsightly blank lines:

```
My.App.Name 1.0.0.0
Copyright © 2015 Robin Munn
Code licensed under the MIT License (http://rmunn.mit-license.org/)




USAGE:
my-app.exe (operation) [-i input-fname] [-o output-fname]





  first-operation    Do something
```

I believe this is the result of a bug in src/CommandLine/Text/MultiLineTextAttribute.cs, where AddToHelpText adds all lines instead of only the non-blank lines. Here's a patch (UNTESTED so far) that I believe may fix the problem:

```
diff --git a/src/CommandLine/Text/MultiLineTextAttribute.cs b/src/CommandLine/Text/MultiLineTextAttribute.cs
index 339c65e..8060735 100644
--- a/src/CommandLine/Text/MultiLineTextAttribute.cs
+++ b/src/CommandLine/Text/MultiLineTextAttribute.cs
@@ -150,7 +150,7 @@ namespace CommandLine.Text
         internal HelpText AddToHelpText(HelpText helpText, Func<string, HelpText> func)
         {
             var strArray = new[] { line1, line2, line3, line4, line5 };
-            return strArray.Aggregate(helpText, (current, line) => func(line));
+            return strArray.Take(GetLastLineWithText(strArray)).Aggregate(helpText, (current, line) => func(line));
         }
 
         internal HelpText AddToHelpText(HelpText helpText, bool before)
```

**Comment by rmunn** [comment]
I can confirm that that patch works to fix this bug. I forked the repo and built a new version with that one-line change, and tested my program against it. And with that change, the superfluous blank lines no longer show up.

**Comment by gsscoder** [comment]
:paperclip: Please read: #250. Thanks for collaboration and patience! :sweat_smile:
Giacomo
_P.S.: valid only for me, if a main contrib. is available he's obviously free to support devs/users of the project._

**Comment by rmunn** [comment]
Turned my patch above into a pull request. I used this in my project and it does what I expected: if my AssemblyLicense and AssemblyUsage attributes specify just one line, then just one line is all I get:

```
My.App.Name 1.0.0.0
Copyright © 2015 Robin Munn
Code licensed under the MIT License (http://rmunn.mit-license.org/)
USAGE:
my-app.exe (operation) [-i input-fname] [-o output-fname]

  first-operation    Do something
```

**Comment by rmunn** [comment]
@gsscoder - Any comment on this issue or on PR #261? It's a one-line change, so I don't think it would be too hard to review...

**Comment by nemec** [comment]
Merged. Unfortunately, @gsscoder holds the keys to the NuGet kingdom and he is away for some time (#271) so there won't be an official package until he gets back.
