### ISSUE TITLE
Support async methods in MapResult extension method

### ISSUE THREAD

**Issue by kensykora** [gsscoder/commandline#248]
Inside my verb handlers I have async calls, and it'd be nice if there were support for async methods this way.

e.g.,

``` csharp
int Main(string[] args) {
  return Parser.Default.ParseArguments<AddOptions, CommitOptions, CloneOptions>(args)
    .MapResultAsync(
      async (AddOptions opts) => RunAddAndReturnExitCodeAsync(opts),
      async (CommitOptions opts) => RunCommitAndReturnExitCodeAsync(opts),
      async (CloneOptions opts) => RunCloneAndReturnExitCodeAsync(opts),
      errs => 1);
}
```

**Comment by gsscoder** [comment]
:paperclip: Please read: #250. Thanks for collaboration and patience! :sweat_smile:
Giacomo
_P.S.: valid only for me, if a main contrib. is available he's obviously free to support devs/users of the project._

**Comment by bpug** [comment]
var test = result.MapResult(
                async (ShallowOptions opts) => await ShallowCheck(opts),
                async (DeepOptions opts) => await DeepCheck(opts),
                err => Task.FromResult(-1));

**Comment by xabikos** [comment]
The suggestion from @bpug worked for me.

**Comment by kensykora** [comment]
Thanks, seems like a viable workaround.
