### ISSUE TITLE
Parsing bool options

### ISSUE THREAD

**Issue by JohnTube** [gsscoder/commandline#258]
Is there a way to parse bool values instead of using all bool options as flags. What if the default value is true and I want to disable/deactivate it by toggle it to false?

**Comment by mInternauta** [comment]
Man, maybe you can use a Interger property with Min and Max, just like:

```
[Option("MySwitch", Max =1,Min = 0)]
public int MySwitch { get; set; }
```

**Comment by mInternauta** [comment]
Or better:

```
[Option("MySwitch", Max =1,Min = 0, Default = 1, Required = false)]
public int MySwitch { get; set; }
```
Can input between 0 and 1, the default value is 1 (ON) , and isnt required by the parser.

Or with boolean:

```
[Option("MySwitch", Default = true, Required = false)]
public bool MySwitch { get; set; }
```

if you went to be required, just change Required to True.

**Comment by gsscoder** [comment]
Please refer to #133 to avoid duplicated issues.

In short, actually boolean options are `false` when omitted and `true` when specified. Internally these are treated as a special case (`Switch`): this is done to follow the standard Unix implementation of command line syntax (normally referred as `getopt` standard in wiki and other issues).
