### ISSUE TITLE
VB.NET implementation question

### ISSUE THREAD

**Issue by egellner** [gsscoder/commandline#272]
I know it is designed for C#. But being usable in VB.NET I am trying to figure out how to declare and get access to the Unbound Values (arguments not associated with an option).
How do use and declare [ValueList] and [Value] in VB.NET?
Thanks

**Comment by nemec** [comment]
Use them the same way you do the `Option` attribute. Sample from [MSDN](https://msdn.microsoft.com/en-us/library/z0w1kczw.aspx?cs-save-lang=1&cs-lang=vb#code-snippet-1):

```vb.net
<System.Serializable()> Public Class SampleClass
    ' Objects of this type can be serialized.
End Class
```

**Comment by mizipzor** [comment]
Due to inactivity I assume the problem was solved. Just reopen if I'm wrong. :)
