### ISSUE TITLE
Bringing localization support via resources

### ISSUE THREAD

**Issue by balticer** [gsscoder/commandline#276]
Hey guys,

i started to bringing localization support via resource files. Please take a look on https://github.com/balticer/commandline/commit/e79465f196230f92eac0e6a4dd015b8cff402cb8.

The basic idea is to have additional parameters for the VerbAttribute and the BaseAttribute. With the ResourceType parameter the type (the resource class itself) will be specified. The ResourceName is specifiying the entry in (property of the resource class). If you set HelpText then it is not allowed to set the Resource\* parameters. Also it is not allowed to set a HelpText, if the Resource\* parameters are set.

**Example:**

``` C#
namespace Example
{
    using CommandLine;

    [Verb("any", ResourceType = typeof(Resource), ResourceName = "VersionHelpText")]
    class AnyCommandLineOptions
    {

        [Option(ResourceType = typeof(Resource), ResourceName = "VerboseHelpText")]
        public bool Verbose { get; set; }

        [Option(ResourceType = typeof(Resource), ResourceName = "SetAHelpText")]
        public int SetA { get; set; }
    }
}
```

Create a resource file, named Resource.resx and create the keys and values. This will be the neutral culture. Create a second resource file named i.e. Resource.de-DE.resx with the same keys and localized values. For some reason you could use https://visualstudiogallery.msdn.microsoft.com/3b64e04c-e8de-4b97-8358-06c73a97cc68. This makes it easier.

This implementation is working, but i want to make it better and more robust. So please take a look, discuss and give me some feedback.

regards
Kai

**Comment by dredav** [comment]
+1

**Comment by balticer** [comment]
No feedback yet, so i'll do a pull request.

regards
Kai
