### ISSUE TITLE
add HelpTextMessage to ValueList to obtain AutoHelpText

### ISSUE THREAD

**Issue by ghuntley** [gsscoder/commandline#282]
It appears that the current implementation for ValueList does not support specifying a help message which means if one uses the AutoHelpText generator then existence of the option is not advertised in the help message.

Something like this is what I've got in mind

      [ValueList(typeof(List<string>), HelpTextMessage = "Lorum Ipsum", MaximumElements = 2)]
      public IList<string> OtherStuff { get; set; }

**Comment by nemec** [comment]
Hi @ghuntley you're looking at version 1.7 of CommandLine, right? 2.0 is in prerelease and now supports a help message (using `HelpText=`) for values. I don't know when it will be out of beta, the owner won't be back until June at the earliest (#291) and he's the only one with access to NuGet.
