### ISSUE TITLE
Demo project is out of date

### ISSUE THREAD

**Issue by Dimpl** [gsscoder/commandline#288]
Specifically, I have noticed that the 'SetName' paramater and the 'Value' attribute don't seem to exist anymore

**Comment by nemec** [comment]
Are you using the latest stable from NuGet? That one is actually the one out of date. The demo project is built for version 2.0 and [SetName](https://github.com/gsscoder/commandline/blob/master/src/CommandLine/OptionAttribute.cs#L86) does exist. You can try out 2.0 as a prerelease on NuGet or get the code from github.
