### ISSUE TITLE
Assigning 2 Options with same value fails

### ISSUE THREAD

**Issue by roni8686** [gsscoder/commandline#293]
Hi,
Couldn't find an answer for this here or at codeplex.

I have these 2 properties:
[Option("IpAddress1")]
public string IpAddress1 { get; set; }
[Option("IpAddress2")]
public string IpAddress2{ get; set; }

and when running with these parameters:
--IpAddress1 "1.1.1.1" --IpAddress2" 1.1.1.1"

I get the "MissingValueOptionError".

when running with:
--IpAddress1 "1.1.1.1" --IpAddress2" 1.1.1.2"
everything works fine.

Any idea why?

**Comment by roni8686** [comment]
It looks like it has something to do with setting the "_.IgnoreUnknownArguments = true;" :

at:
new Parser(
                _ =>
                {
                    _.CaseSensitive = false;
                    _.HelpWriter = helpWriter;
                    _.IgnoreUnknownArguments = true;
                }).
                ParseArguments<T>(commandLineArguments).
                WithParsed(_ => parsedFromCommandLineArguments = _).
                WithNotParsed(
                    _ =>
                    {
                        parseSucceeded = false;
                        if (_.Any(
                            __ => __.Tag == ErrorType.HelpRequestedError ||
                                  __.Tag == ErrorType.HelpVerbRequestedError))
                        {
                            isHelpRequestedDetected = true;
                        }
                    });

**Comment by usagirei** [comment]
Its possible that this is related to issue #277 too

**Comment by b0urb4k1** [comment]
I ran into the same problem and constructed a minimal example causing the problem.
[Code](https://gist.github.com/b0urb4k1/a634ad8ce213730186cb4a1f4b6902d9)
It seems to be related to the normalization in the Tokenizer (Tokenizer.Normalize).
Both cases result in an emtpy set of toExclude tokens but somehow in the case of
duplicated values it deletes one of the values causing the error in the end.
 I assume the error is that Except returns distinct results.
https://msdn.microsoft.com/en-us/library/bb300779(v=vs.100).aspx (see comments)

[Pull Request](https://github.com/gsscoder/commandline/pull/315)

**Comment by nemec** [comment]
Hi @b0urb4k1 your pull request looks great. Can you add two unit tests based on your minimal example? One that tests `workingArgs` (as the baseline) and another testing `failingArgs`.

**Comment by b0urb4k1** [comment]
I added the tests as requested.

**Comment by nemec** [comment]
Merged. Thank you for your contribution, @b0urb4k1!
