### ISSUE TITLE
How to access unbound parameters?

### ISSUE THREAD

**Issue by MikhailEdoshin** [gsscoder/commandline#294]
The Grammar Details guide mentions unbound parameters, that is positional parameters not bound to an option, e.g.:

    myprogram abc def --foo=bar ghi

Here we have a single `--foo` option with value `bar` and three unbound parameters, `abc`, `def`, and `ghi`. The question is how do I get these parameters after parsing? The documentation only says that the parser has means to handle them, but doesn't mention any details.

**Comment by nemec** [comment]
Add an enumerable string property and tag it with a `Value` attribute. You can use the min/max attributes to quantify how many unbound values you want to accept (set just Min=0 for any number)

Sample [here](https://github.com/gsscoder/commandline/blob/72f38563bff69ef64f0243c386095b1ea7f3b8f7/tests/CommandLine.Tests/Fakes/Options_With_Sequence_And_Only_Min_Constraint_For_Value.cs)

    class Options_With_Sequence_And_Only_Min_Constraint_For_Value
    {
        [Value(0, Min=1)]
        public IEnumerable<string> StringSequence { get; set; }
    }

**Comment by MikhailEdoshin** [comment]
Thank you, this is very helpful.
