### ISSUE TITLE
Add gitter chat

### ISSUE THREAD

**Issue by hellboy81** [gsscoder/commandline#295]
subj

**Comment by nemec** [comment]
What is gitter? What benefits does it offer?

**Comment by RandomlyKnighted** [comment]
From [Wikipedia](https://en.wikipedia.org/wiki/Gitter):

`Gitter is an instant messaging and chat room system for developers and users of GitHub repositories.
Individual chat rooms can be created for individual git repositories on GitHub. Chatroom privacy follows the privacy settings of the associated GitHub repository: thus, a chatroom for a private (i.e. members-only) GitHub repository is also private to those with access to the repository. A graphical badge linking to the chat room can then be placed in the git repository's README file, bringing it to the attention of all users and developers of the project. Users can chat in the chat rooms, or access private chat rooms for repositories they have access to, by logging in to Gitter via GitHub[2] (which does not involve sharing the user's GitHub password with Gitter).`

**Comment by nemec** [comment]
[Done](https://gitter.im/gsscoder/commandline). I still haven't figured out why they want write access to the repo, but one step at a time I guess.
