### ISSUE TITLE
 Validate if required parameters are setted on object, even in case they were not supplied as CLI arguments

### ISSUE THREAD

**Issue by victorarcasrios** [gsscoder/commandline#297]
Is there a way to make CommandLine to validate if required parameters are setted on object, even in case they were not supplied as CLI arguments?

In my case, you can specify the parameters via a JSON configuration file. So although the parameters were not supplied into args[], they're already at the options object.
But the CommandLine.Parser.Default.ParseArguments method check if they were supplied within the args array and always says that those required arguments are missing.

**Comment by nemec** [comment]
So the scenario is that your JSON serves as the base config and CommandLine parsing is used to selectively override certain configuration settings?

That's beyond the scope of this project as `Required` means the user is required to provide the option *on the command line*. My suggestion would be to leave the property as optional and then use a library like [FluentValidation](https://github.com/JeremySkinner/FluentValidation) after the fact. This project makes no attempt at validating the content of your parameters, only the type and number, and I don't think it will ever be added (see #128).

Sorry about that! But I think using an actual validation library will offer far more value than anything that can be tacked on to a command line parsing library, such as the ability to validate options that _can't_ be set from the command line.
