### ISSUE TITLE
Generic ParseArguments does not work

### ISSUE THREAD

**Issue by ionuttamas** [gsscoder/commandline#304]
`var result = CommandLine.Parser.Default.ParseArguments<Options>(args);`

does not work in latest stable version "1.9.71"

**Comment by nemec** [comment]
Do you have any details about what isn't working? A stack trace?

**Comment by ionuttamas** [comment]
It does not compile.

**Comment by nemec** [comment]
Ah, I understand. ParseArguments isn't a generic method. You need to create a new Options object then pass it as the second parameter.

    var options = new Options();
    var result = CommandLine.Parser.Default.ParseArguments(args, options);

**Comment by nemec** [comment]
I'm going to close this, but please reopen if the above example doesn't solve your problem.

**Comment by waynebloss** [comment]
The README needs to be updated because that is the first example that I tried.
