### ISSUE TITLE
[Question] - Parsing multiple verbs

### ISSUE THREAD

**Issue by dazinator** [gsscoder/commandline#306]
I am wondering whether what I would like to do is possible!

I would like to have multiple verbs:

- DoThis
- DoThat

But i'd like them to be used within the same command:

```
MyExe DoThis --somearg "foo" --anotherarg "bar" DoThat --someotherarg "foo"
```

I gave this a try very briefly, but it seems that when you parse, it basically parses one of the verbs, and you can't continue to try and parse any more:

```
  var parser = new Parser(with => with.IgnoreUnknownArguments = true);
 var parsedResult = parser.ParseArguments<DoThis, DoThat>(args);
 parsedResult
                .WithParsed<DoThis>(
                    o =>
                    {
                        // This fires..
                    });

 parsedResult
                .WithParsed<DoThat>(
                    o =>
                    {
                        // This doesn't fire..
                    });
// etc
```

This is probably by design I am guessing? Or is there some workaround?

**Comment by nemec** [comment]
You're right, this is by design. You could do what `git` does and introduce a third "combination" verb, like how `git pull` is equivalent to `git fetch; git merge` with some additional magic.

**Comment by dazinator** [comment]
Ok thanks for clarifying, I think i'll steer clear of this idea for now, and just use options ;)
