### ISSUE TITLE
[Question] - Polymorphic options possible?

### ISSUE THREAD

**Issue by dazinator** [gsscoder/commandline#307]
I am wondering if you can define a single options property, which holds a polymorphic instance.

For example, if I have:

```
OptionsA --> BaseOptions
OptionsB --> BaseOptions
OptionsC --> BaseOptions
```

Then I have multiple verbs, and I want them all to allow for an instance of `BaseOptions`

```
GoHere --> BaseVerb
GoThere --> BaseVerb
```

At the moment, I think I am right in saying that for each subclass of `BaseOptions` I have to add a property of that subtype to the `BaseVerb` like this:

```
 public abstract class BaseVerb
    {

        [Option('a', "option-a")]    
        public OptionsA OptionsA { get; set; }

        [Option('b', "option-b")]    
        public OptionsB OptionsB { get; set; } 

        [Option('c', "option-c")]    
        public OptionsC OptionsC { get; set; } 
}
       
```

And then, thinking further, I'd probably have to put them in mutually exclusive sets so that you can only pass a single set of options with the verb, and not multiple sets of options.

What I would prefer would be to just do this:

```
 public abstract class BaseVerb
    {

       //  no idea what to put for this attribute as it would have to deal with multiple potential types..
        [Option('???', "option-??")]   
        public BaseOptions Options{ get; set; }     
    }
       
```

This way, I don't need to keep modifying this class as I add new sub types for the options..

Is this kind of thing possible!? :)

**Comment by dazinator** [comment]
Further to this, it seems my assumption that it would work the first way may also be wrong.. I thought I could use the `[Option]` attribute on a complex type:

```
        [Option('a', "option-a")]    
        public OptionsA OptionsA { get; set; }
```

But when I try this, It fails to pass, saying I haven;t provided any value for `--options-a` ?

**Comment by nemec** [comment]
Hi @dazinator what you're looking for is not possible here. We don't do any special logic for base classes and polymorphism. A superclass would allow you to _share_ properties among multiple verbs or even between multiple parsers, but the parsing logic simply reflects across the properties (and parent properties) of the specific class you pass in.

**Comment by dazinator** [comment]
Thanks @nemec

**Comment by dazinator** [comment]
Is it worth me starting a PR to try and allow the parsing of nested Options classes? i.e properties that are marked with an `[Option]` attribute, but are actually complex types (not simple scalars or arrays) that themselves have their own properties defined marked with `[Option]` attributes?

Or would you not really consider this a worthwhile feature?

**Comment by nemec** [comment]
I've been trying something similar an another one of my projects and one issue I ran into was "how does each nested option get initialized?" If we require the nested ones to have a default constructor, I think it would work.

A few things to keep in mind:
1. We'd need a new attribute to tag the complex type with because, I assume, it won't have a short/long argument of its own.
2. Will each nested type be "mutually exclusive" with the others? Or does it act like just one flattened type as far as parsing goes? (perhaps an option)
3. Help generation. Will be interesting to see if there's a good way to describe the logic in the auto-generated help page :)
