### ISSUE TITLE
[Question] - How to parse options as properties of a verb.

### ISSUE THREAD

**Issue by dazinator** [gsscoder/commandline#308]
Is there any way to use the `[Option`] attribute on a property that is itself an options class? i.e a complex type (rather than a scalar, or values list as is the norm)?

e.g:
```
    [Option('a', "option-a")]    
    public OptionsA OptionsA { get; set; }

```

I'd like to do this so that I can group my options together:

```

public class SomeVerb
{

    [Option('a', "car-options")]    
    public CarOptions CarOptions { get; set; }

    [Option('p', "plane-options")]    
    public PlaneOptions PlaneOptions { get; set; }

    [Option('l', "logging-options")]    
    public LoggingOptions LoggingOptions { get; set; }
}

```

Each one of those classes is just your typical options class.

**Comment by nemec** [comment]
I see how this can be useful, but no it isn't supported. This is typically the use case for verbs, where each verb would define its own unique options class.

    myprog.exe car --transmission=manual
    myprog.exe plane --wing-size=large

**Comment by dazinator** [comment]
Ok thanks. I am actually already using verbs, and the "group options together" explaination was a bit of a simplification but possibly valid motive for why you may attempt this. The real reason I was trying this, as you can probably guess, was in relation to #307, where I was trying to see if I could give my base verb some options that were polymorphic. Looks like i'll have to try and do this by implementing all options in the base verb directly, and using mutually exclusive sets, but this will make the verbs quite large and messy so was experimenting to see if I could avoid! Thanks for the clarification ;)
