### ISSUE TITLE
Spaces in option values are not removed

### ISSUE THREAD

**Issue by OsirisTerje** [gsscoder/commandline#313]
If I add a value for a string option like
-o "My value with spaces"
I have to enclose it in apostrophes, which is fine.  
But the parsing should then not include these apostrophes,  but it does.

**Comment by nemec** [comment]
Hi @OsirisTerje can you share the exact array that you're sending to the parser? Since console applications do a little pre-parsing of argument strings (to convert to the `string[] args` parameter, you may be passing some unexpected data to the service.

**Comment by OsirisTerje** [comment]
The case seems to be a Windows issue, where the a value ends in a \ just before the end apostrophe, then it is assumed to be an escape char, and passed through, which means the subsequent options are treated as part of the first one.  
The command line I send in is:  
-i d:\tfskb\Models\Model -o "D:\Work\Tfs1\Nemo\ReleaseBranch\Nemo v2.2.2\Dory\System\Object\" -d ModelDeployment.xml -p AHV05

And the issue is around the -o option, which is a string option.  

What I see in the code is this:
![image](https://cloud.githubusercontent.com/assets/203432/15152066/3c24d6a0-16d4-11e6-8708-c14b3f0c05a4.png)

Notice the 4th parameter there, which now includes the subsequent.  If I add a space char after the backslash, it comes out correct.  And note, this is before parsing !  So this is how it comes from Windows command line.  I see the issue has also been discussed at SO:  http://stackoverflow.com/questions/1291291/how-to-accept-command-line-args-ending-in-backslash and http://stackoverflow.com/questions/9287812/backslash-and-quote-in-command-line-arguments  

If I add an extra space it comes out correct
![image](https://cloud.githubusercontent.com/assets/203432/15152260/d7266024-16d4-11e6-9852-8602d8b36272.png)

And the parsing works as it should
![image](https://cloud.githubusercontent.com/assets/203432/15152315/19ddb868-16d5-11e6-8032-41cc2b9d8c49.png)

So, this issue can be closed, I don't think the parser can do anything about what Windows command line is sending over.
