### ISSUE TITLE
The type Parsed is not defined 

### ISSUE THREAD

**Issue by parmigianig** [gsscoder/commandline#314]
Hello, 

sorry to open this, i'm quite new to **F#** and i'm getting this error.
_The Types Parsed<'a> and NotParsed<'a> are not defined_, when trying to run my code.
i already referenced what i need in my project, plus:

```
open System;
open CommandLine;
open CommandLine.Text;

#if INTERACTIVE
#r @"...\CommandLineParser20.2.0.0.0\lib\net40\CommandLine.dll"
#endif
```

Any Clues? thank you
Giacomo

**Comment by nemec** [comment]
Hi Giacomo, I'm not too familiar with F# but that single CommandLine dll should be all you need. Does anything _else_ work from that dll or do you get the above error no matter what you try to do with the library?

**Comment by parmigianig** [comment]
The rest of the library works and i got intellisense. Just Parsed and NotParsed are not being seen by the compiler, apparently. maybe i need to add something else? Thank you

**Comment by nemec** [comment]
Hey, where are you getting the binary from? The latest beta on NuGet is 2.0.275 but I see you're using a version I don't recognize: 20.2.0.0.0

**Comment by nemec** [comment]
Here's the latest beta (`commandlineparser.2.0.275-beta\lib\net40`) in a decompiler. I wanted to make sure we didn't do something weird like stick it in a helper DLL, but nope it's right there. Same namespace too.

![](http://i.imgur.com/uNYnWSy.png)

**Comment by parmigianig** [comment]
Ok  it was an issue with version. i was using 2.0.0 . my fault. i updated with latest beta and compiler is now giving no complaints at all. thanks
