### ISSUE TITLE
HelpText MaximumDisplayWidth Should Be Set To Current Console Width By Default

### ISSUE THREAD

**Issue by CreepyGnome** [gsscoder/commandline#320]
FEATURE REQUEST :)

I noticed that the HelpText MaximumDisplayWidth is always 80, and I see in the code that it defaults to this.  I think that if this would be setup automatically to the current width of the console this would be a better user experience.  

All the command line tools I have used over the years will change the next time I run them if I just resize the console window, which is nice for the help to size with it.

I was trying to find a workaround but didn't see any wiki/docs on how to get access to the HelpText that is created with AutoBuild<T> as it appears to be done inline on the Parser.DisplayHelp<T>. 

An alternative would be to provide the console width by setting a value in the Parser.Default.Settings, or as a argument to the ParseArguments method as well which can then be used by the HelpText class when its needed.

**Comment by nemec** [comment]
This is a really great idea. You're right that customizing the help screen isn't very easy right now, but in the meantime this would work well as an additional [ParserSetting](https://github.com/gsscoder/commandline/blob/master/src/CommandLine/ParserSettings.cs). I'd like to have it use `Console.Width` if a value isn't provided, but I'm not sure how @gsscoder feels about breaking backwards compatibility for this - probably better to stick with a default of 80 for now.

I don't know if I'll have time to implement it, but it should be quick and easy for someone else to pick up.

**Comment by CreepyGnome** [comment]
Well I may be missing something as I am not sure I see how implementing this feature breaks backwards compatibility, and it is still in a beta for 2.0 anyway if it did so still not to late.

If the default was the Console.Width instead of 80, everything will size correctly, and since it should be properly using MaximumDisplayWidth anyway everything should have sized correctly at any size. Therefore going forward with the new implementation it would simple not be fixed, but dynamic at each run. If an easy way to change this is also exposed, for example as a Parser Setting, then it can be set back to 80 easily if someone really liked it to not wrap and look funny on console windows larger than 80 columns.  I mean what developer or techie still runs a console at 80 columns any more with the large screens we have today.

I am interested to hear @gsscoder thoughts on the feature.

**Comment by nemec** [comment]
The `Console.WindowWidth` getter throws an exception when `Console.Out` is redirected. In fact, I think that's how this project's unit tests are run for every pull request so every test in [this file](https://github.com/gsscoder/commandline/blob/master/tests/CommandLine.Tests/Unit/Text/HelpTextTests.cs) would need to explicitly set a width to keep from crashing.

Good point about still being in beta. If someone wants to submit a pull request with `Console.WindowWidth` set to the default, I'll merge it provided checks are in place to prevent crashing-by-default (with accompanying tests that manually call `Console.SetOut`). I believe you can just do something like the following to prevent a crash:

    if(!settings.ConsoleWidth.HasValue)
    {
        if(!Console.IsOutputRedirected)
        {
            width = Console.WindowWidth;
        }
        else
        {
             width = DefaultValueOf80;
        }
    }
    else
    {
        width = settings.ConsoleWidth.Value;
    }

**Comment by CreepyGnome** [comment]
I will see if I can get some time this week to make the change and submit a pull request with the feature implemented.

**Comment by CreepyGnome** [comment]
Okay pull request https://github.com/gsscoder/commandline/pull/321 made for changes to implement the features discussed in this issue.

**Comment by nemec** [comment]
Merged! Thank you for your contribution.
