### ISSUE TITLE
Don't require name for argument if there is only one required argument

### ISSUE THREAD

**Issue by frankbryce** [gsscoder/commandline#335]
I would like it if the command options can be used without any argument name if there is only one required parameter.  Consider the following example.

```
/// <summary>
/// options for a Print command
/// </summary>
class PrintOptions
{
    /// <summary>
    /// Text to write to standard out
    /// </summary>
    [Option('t', "text", Required = true, HelpText = "Text to write to standard out")]
    public string Text { get; set; }

    [Option('p', "prepend", Required = false, DefaultValue = false, HelpText = "if true then the text is prepended to standard in before sending to standard out")]
    public bool Prepend { get; set; }
}
```

which can be used like this

`Print -t "I want to print this to the Console like echo does"`

or this

`Print -t "to the Console like echo does" | Print --prepend -t "I want to print this "`

I would like it if the command can be used like this

`Print "I want to print this to the Console like echo does"`

Is this currently possible?  If not, can I submit a feature request?

**Comment by nemec** [comment]
It's possible but also a little weird. Options without an argument name are called 'values' so you need to make the `Text` property an `Option` _and_ a `Value`.

```csharp
// Define other methods and classes here
/// <summary>
/// options for a Print command
/// </summary>
class PrintOptions
{
	/// <summary>
	/// Text to write to standard out
	/// </summary>
	[ValueOption(0)]
	[Option('t', "text", Required = false, HelpText = "Text to write to standard out")]
	public string Text { get; set; }

	[Option('p', "prepend", Required = false, DefaultValue = false, HelpText = "if true then the text is prepended to standard in before sending to standard out")]
	public bool Prepend { get; set; }
}

You can then parse arguments like this:

```csharp
var opt = new PrintOptions();
CommandLine.Parser.Default.ParseArguments(new[] {"-t", "my text" }, opt);
CommandLine.Parser.Default.ParseArguments(new[] {"-tmy text" }, opt);
CommandLine.Parser.Default.ParseArguments(new[] {"my text" }, opt);
```

Unfortunately, because the third case does _not_ parse as an option you can't set `Required=true` - you'll need to manage validation yourself after parsing.

**Comment by frankbryce** [comment]
Thanks for your response.

I saw in trunk, and also the pre-release version of this, that there is a `ValueAttribute` which seems to be closer to what I'm looking for, but also imperfect.  It solves the problem of being able to mark it as "required" but it also makes the value required to be first, followed by the optional arguments.I think I'm willing to live with this though.  I think I'll just move to the prerelease version.

Any chance that a feature like this is in the works, though?

**Comment by nemec** [comment]
Do you know if any other argument parsers have a feature similar to what you're requesting? This library tries to stick with the [getopt](https://en.wikipedia.org/wiki/Getopt) syntax which doesn't support a required argument with an optional name.

If you use `ValueAttribute` you definitely don't _have_ to put the value first, but if you're having trouble (which sometimes happens in cases where parsing is ambiguous), set `parserSettings.EnableDashDash` to `true` and then call the application with arguments like these:

    -m optional1 -n optional2 -- requiredValue

**Comment by frankbryce** [comment]
Nope, I don't.  However, in powershell for example the behavior is similar to what I'm describing.

For example

    gci . -Filter *.txt

is the same as

    gci -Filter *.txt .

I'm assuming because the "path" is the default argument if no name is specified... though I'm not sure exactly what the parsing engine does here it seems like it's doing something similar to what I proposed.

**Comment by nemec** [comment]
I see what you're talking about, but the example you showed (reordering parameters) is already possible in this library with the default settings.

Powershell allows _every_ parameter to be specified by name, including positional parameters, which is why Powershell works the way it does. It seems like their parser fills in every named argument and then takes the positional arguments and puts them in the remaining unfilled positional slots.

**Comment by frankbryce** [comment]
I agree that reordering parameters is possible, but without explicitly specifying a name can `CommandLine` work in the way I specified in the powershell example?

**Comment by nemec** [comment]
Yes, I just tried it.

```csharp
void Main()
{
	var result = Parser.Default.ParseArguments<Options>(". --Filter *.txt".Split());
	result.WithParsed(opt => opt.Path.Dump());

	result = Parser.Default.ParseArguments<Options>("--Filter *.txt .".Split());
	result.WithParsed(opt => opt.Path.Dump());
}

class Options
{
	[ValueAttribute(0)]
	public string Path { get; set;}

	[OptionAttribute("Filter")]
	public string Filter { get; set; }
}
```

**Comment by frankbryce** [comment]
Thanks.  Cheers.
