### ISSUE TITLE
InvalidCastException if int option equals to 'false'

### ISSUE THREAD

**Issue by ironromeo** [gsscoder/commandline#339]
Providing invalid value "false" to int option (-v in my example) cause InvalidCastException:
myapp -v false
Providing any other string run as expected and return "Option 'v, validate' is defined with a bad format."
myapp -v anyotherstring

**Comment by Mizipzor** [comment]
If you type something that is not a bool, like a string, then the error would be created [here](https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Core/OptionMapper.cs#L42). But that doesnt happen in this case. I've been staring at that method for a while now. I'm new to functional programming, I just can't read it. Hardly any independent lines to step through with a debugger.

**Comment by nemec** [comment]
I think I may have figured it out. When looking at the [type conversion](https://github.com/gsscoder/commandline/blob/0750d78366617b7deec4a00059f12c8032d0ea30/src/CommandLine/Core/TypeConverter.cs#L73) code I see that the code explicitly checks whether the value is a boolean and, if so, converts to a bool.

TBH I'm not sure why booleans are called out explicitly (doesn't `Convert.ChangeType` handle them already?) but I think that we should check `conversionType == typeof(bool) && value.IsBooleanString()` instead.

**Comment by nemec** [comment]
Pull request has been merged.
