### ISSUE TITLE
UsageAttribute - How to use?

### ISSUE THREAD

**Issue by Pitterling** [gsscoder/commandline#346]
Hi, can't get the usageattribute working

i just placed the code snippet  
[Latest-Version#usage-attribute](https://github.com/gsscoder/commandline/wiki/Latest-Version#usage-attribute)

to the Readtext.Demo example. It seems that the Usage attribute could not be found?

**Comment by nemec** [comment]
Are you using the latest beta and importing the `Commandline.Text` namespace?

**Comment by Pitterling** [comment]
Thanks. namespace was missing and i had some trouble to convert it to VB.net ..

Now it seems that USAGE is only generated in case of an error. Why not showing this all the time on the help screen?

**Comment by Pitterling** [comment]
@nemec it seems "Usage" is only generated for Verb Commands but not for normal options.
At least the Unittests are all for Verb commands. My help screen never contains any USAGE: section

**Comment by nemec** [comment]
It seems to work for me on the latest NuGet package (2,0,275-beta). See example:

```csharp
class Options
{
	[Option('i')]
	public string InputFile { get; set;}

	[Option('o')]
	public string OutputFile { get; set;}

	[Option('w')]
	public bool LogWarning { get; set; }
	
	[Option('e')]
	public bool LogError { get; set; }

	[Usage(ApplicationAlias = "yourapp")]
	public static IEnumerable<Example> Examples
	{
		get
		{
			yield return new Example("Normal scenario", new Options { InputFile = "file.bin", OutputFile = "out.bin" });
			yield return new Example("Logging warnings", UnParserSettings.WithGroupSwitchesOnly(), new Options { InputFile = "file.bin", LogWarning = true });
			yield return new Example("Logging errors", new[] { UnParserSettings.WithGroupSwitchesOnly(), UnParserSettings.WithUseEqualTokenOnly() }, new Options { InputFile = "file.bin", LogError = true });
		}
	}
}
```

```csharp
var parser = new Parser(config => config.HelpWriter = Console.Out);
	var result = parser.ParseArguments<Options>("--help".Split());
```

```
CommandLine 2.0.275-beta
Copyright (c) 2005 - 2015 Giacomo Stelluti Scala
USAGE:
Normal scenario:
  yourapp -i file.bin -o out.bin
Logging warnings:
  yourapp -w -i file.bin
Logging errors:
  yourapp -e -i file.bin
  yourapp -e -i file.bin

  -i           
  -o           
  -w           
  -e           
  --help       Display this help screen.
  --version    Display version information.
```

You see the USAGE is included here.

**Comment by Pitterling** [comment]
Sometimes its so easy ... my Examples function was Private .. no error message, no hint ... its just ignored ..
No i changed it to public and it works.

Thanks

**Comment by Pitterling** [comment]
one more thing ... long options are missing the equal sign, e.g. 

```
-i --> -i file.bin
--input --> --input=file.bin
```

all examples in the documentation show the same behavior. Therefore the generated usage text is not valid?

**Comment by nemec** [comment]
Ah, yes if it's private we cannot see the function in reflection (and therefore can't warn you). Glad you got this fixed!
