### ISSUE TITLE
Problem with multiple verbs in single command line

### ISSUE THREAD

**Issue by paulduran** [gsscoder/commandline#349]
Hi,

I'm trying to implement a verb based command line where each verb has options. eg: 

* `MyCommand download --directory c:\temp`
* `MyCommand test --file c:\temp\download.dat`
* `MyCommand package -- folder c:\temp`

I don't seem to be able to combine them in a single command line. eg:

`MyCommand download --directory c:\temp test --file c:\temp\download.dat package --folder c:\temp`.

Is this not a capability of the command line parser at the moment? It seems to try to match all of the --arguments to the first verb.

**Comment by ericnewton76** [comment]
imo, there should be no support for multiple verbs.

nobody does

`git fetch --all pull --all merge --s=ours rebase a443c23 status`

if your point is to download a file, stay focused on downloading a file.
if your point is to create a package, stay focused on creating a package.

keep it simple.

**Comment by nemec** [comment]
No, this is not a feature. I'm not aware of any existing applications that support that kind of thing - if you've seen one, can you share it?

What you _may_ have seen are nested subcommands. Something like [this](http://stackoverflow.com/questions/10606535/git-svn-rebase-vs-git-rebase-trunk):

    git svn rebase

In this case, the verb `rebase` only exists within the context of the `svn` verb - while `git rebase` exists, it runs an entirely different code path and isn't equivalent.

Commandline doesn't support nested verbs either, unfortunately. If it did, there would be increased ambiguity between verbs and positional options: is `git pull master` two verbs or one with a parameter?

**Comment by paulduran** [comment]
Sorry for the delay in getting back to you but thanks for your feedback guys.

The question related to my own project that I am building. It's basically a tool for database backup/restore (not quite the example that I provided) and has several functions that can run together, or independently:

* download backup zip file(s) from amazon S3 (from an optional point in time)
* extract the backups - either the ones that have just been downloaded or some pre-existing zip files. (optional file names or, if not specified, the ones from the 'download' step)
* restore the backups to a database (optional data directory and database name and optional file names - if not specified, uses the ones from the 'restore' step)
* plus several other functions

so the different verbs have different options that they respect.

Anyways, the way I approached it was to split the command line args up by verbs and everything in between was supplied arguments to the adjacent verb. It's not a perfect solution but I thought I'd include the code here in case anybody else has a similar requirement in the future.

```
            var verbs = new[] {"help", "download", "extract", "restore"};
            var verbCommands = new List<string[]>();
            List<string> currentCommand = null;
            foreach (var arg in args)
            {
                if (verbs.Contains(arg))
                {
                    if (currentCommand != null)
                        verbCommands.Add(currentCommand.ToArray());
                    currentCommand = new List<string>();
                }
                if(currentCommand != null)
                    currentCommand.Add(arg);
            }
            if (currentCommand != null)
                verbCommands.Add(currentCommand.ToArray());
            int result = 0;
            foreach (var cmd in verbCommands)
            {
                result = Parser.Default.ParseArguments<DownloadOptions, ExtractOptions, RestoreOptions>(cmd).MapResult(
                    (DownloadOptions opts) => RunDownloadAndReturnExitCode(opts),
                    (ExtractOptions opts) => RunExtractAndReturnExitCode(opts),
                    (RestoreOptions opts) => RunRestoreAndReturnExitCode(opts),
                    errs => 1);
                if (result == 1)
                    return result;
            }
```
