### ISSUE TITLE
Wrong handling of external streams

### ISSUE THREAD

**Issue by rlsf** [gsscoder/commandline#355]
Hello,
the code actively disposes streams given in settings.HelpWriter parameter, although it's not its responsibility to do it.

e.g.
var cliParser = new Parser((settings) => settings.HelpWriter = Console.Error);
in this example, the code should not try to close Console.Error.

the same applies to any stream given to HelpWriter, since the stream isn't created inside the class, the class should not take the liberty to dispose it, but let the caller do it.

RL

**Comment by nemec** [comment]
Very good point. I've merged @anthonylangsworth's pull request to remove this, it will be included in the next published NuGet package.
