### ISSUE TITLE
.NET Core version of package?

### ISSUE THREAD

**Issue by erick-thompson** [gsscoder/commandline#366]
I was attempting to use CommandLineParser in a .net core console app (.NET Standard 1.6). I couldn't find a compatible version in the main nuget feed. I see there is a branch for .net core support - is there any idea as to when it might be released/published to nuget?

**Comment by schwamster** [comment]
+1

**Comment by MichaelTuransky** [comment]
+1

**Comment by joaopgrassi** [comment]
There's a discussion about it here:
https://github.com/gsscoder/commandline/pull/340

**Comment by nemec** [comment]
New prerelease package pushed out. Let me know if you have any issues!

https://www.nuget.org/packages/CommandLineParser/2.1.1-beta
