### ISSUE TITLE
Nuget Package license link gives 404.

### ISSUE THREAD

**Issue by nvrnight** [gsscoder/commandline#368]

**Comment by nemec** [comment]
Well that's annoying. I'll fix that soon.

**Comment by nemec** [comment]
Fixed.

**Comment by gregmac** [comment]
Latest prerelease on nuget.org (https://www.nuget.org/packages/CommandLineParser/2.1.1-beta) has its license pointed at https://raw.github.com/gsscoder/commandline/master/doc/LICENSE which is 404.
