### ISSUE TITLE
Nuget 2.0.275-beta, FSharp.core reference missing assembly

### ISSUE THREAD

**Issue by manytwo** [gsscoder/commandline#369]
Hi, I m currently working with Nuget beta package to use new simplified API. 
I do not use FSharp, and all works fine when I build from Visual Studio.
I need to include my tool in a company project, and must provide it as single exe file.
So I used ILMerge to include dll into a single exe file, but here an error occurs:

> Unresolved assembly reference not allowed : FSharp.Core

After few research I have found issue [#319](https://github.com/gsscoder/commandline/pull/319).
To make my ILMerge work I have to clone project, and build it with SKIP_FSHARP preprocessor variable (or add FSharp.core to my project).

How is this managed in Nuget stable package?

**Comment by nemec** [comment]
The stable package doesn't have a dependency on FSharp - between 1.x and 2.x the library was completely rewritten.

**Comment by manytwo** [comment]
Sorry, my question was poorly formulated, it is about future release. 
I don't want to embed it as it increase my tool x 2 (and CommandLine x 7).
I understand this is a special case, ILMerge is checking for assemblies references and fail to merge. In many cases you just have to not add FSharpCore.dll.
I just want to now if I need to stop use NuGet and work with repository instead for future release. 
Thanks.

**Comment by nemec** [comment]
Ah, no there are no plans to remove FSharp.core from the NuGet package. If you need it gone, you'll have to compile it yourself with the SKIP_FSHARP flag

**Comment by manytwo** [comment]
Ok, thanks.
And thanks again for your library,really good job!
