### ISSUE TITLE
Inconsistent documentation.

### ISSUE THREAD

**Issue by iustin94** [gsscoder/commandline#375]
So, I opened an issue but felt that I was not explicit enough. I've been using this library for a bit now and so far what I keep having difficulties is to find a consistent source of documentation. 

On the official Codeplex page the documentation seems to reference the version 1.9 syntax, however here on github you give example for the 2.0 version. I do have the version 2.0 in my project but the exact same code is posted here will not work in my build since the syntax seems to be different. Not really sure if I should have submitted this as an issue or as a discussion.

**Comment by nemec** [comment]
2.0 was a rewrite from the ground up and things changed a lot, so older documentation from 1.x won't usually apply.

The 2.0 documentation is listed [here](https://github.com/gsscoder/commandline/wiki/Latest-Version).

**Comment by iustin94** [comment]
I read about that and tried the documentation you linked. However I am having issues with parsing verbs to their respective option sets. More specifically, when I want to do `Parser.Default.ParseArguments<PublishSubOptions, ConsumeSuboption>(args)
.MapResult....` or `.WithParsed` I get the error " ParseResult<object> does not contain a definiion for MapResult".
