### ISSUE TITLE
Issue passing URLs as options

### ISSUE THREAD

**Issue by CodingGorilla** [gsscoder/commandline#378]
So I have a very simple program that I'm trying to pass partial URLs to, the options look like:

```
        [Value(0)]
        public string Endpoint { get; set; }

        [Value(1)]
        public string Username { get; set; }

        [Value(2)]
        public string Password { get; set; }
```

The `EndPoint` value would look like `"/users/dealer"`, but I always get an error when I pass a value like that, even if enclosed in double-quotes.  The error is "UnknownOptionError" and the `Token` is "u".  If I switch on `IgnoreUnknownOptions` then I don't get an error, but my `Endpoint` option ends up being "sers/dealer".

Am I missing something, is there something that I need to change to make it accept these parameters, or is this a legit bug?

**Comment by nemec** [comment]
What version of the library?

**Comment by CodingGorilla** [comment]
Version 2.0.0.0, packages.config shows:

`<package id="CommandLineParser20" version="2.0.0.0" targetFramework="net461" />`

**Comment by nemec** [comment]
Install `CommandLineParser 2.1.1-beta` and try again. You're using an unofficial build that isn't supported (and is likely out of date).

**Comment by CodingGorilla** [comment]
Yep, that did the trick.  Thanks!
