### ISSUE TITLE
Anyway to add -txt or -log etc as a bool argument 

### ISSUE THREAD

**Issue by SubithaMS** [gsscoder/commandline#379]
I need an option like 

App.exe -txt

So basically I need to pass "-txt" as an bool argument .

I tried to add like as follows

      [Option("txt", DefaultValue = false, HelpText = "download all text files", LongName = "txt", MetaValue = "nothing",MutuallyExclusiveSet = "", Required = false]
        public bool TextFiles { get; set; }

But it saying ha LongName is  not a valid named argument

Any help is appreciable.

**Comment by nemec** [comment]
The first (constructor) argument to `OptionAttribute` is the long name. Leave it out of the "optional parameter" section and everything should work as expected.

You will, however, need to use two dashes (`--txt`) instead of the one you showed above.

**Comment by nemec** [comment]
Closing this. Please reopen if the note above did not solve your problem.
