### ISSUE TITLE
Ambiguous first character for the long name of an option can cause it to be incorrectly recognized

### ISSUE THREAD

**Issue by markdwood** [gsscoder/commandline#380]
Using current stable version 1.9.71.2, I had defined two options:

        [OptionList('i', "ignore", Separator = ';', HelpText = "...")]
        public IList<string> IgnoreURIs { get; set; }

        [Option("ignoreDiag", DefaultValue = false, HelpText = "...")]
        public bool IgnoreCustomStoryProperties { get; set; }

For the second option, I did not specify a single character option, with the intent that this option would only apply if the full --ignoreDiag option was provided.

However, if the option -ignoreDiag is passed, the parser does not correctly process it.

It appears that in OptionGroupParser.Parser, an option group is found using the first character:

            var optionGroup = new OneCharStringEnumerator(argumentEnumerator.Current.Substring(1));

specifically, it appears to interpret this option as the -i option, which is not correct.   I would have expected an error to have been generated in this case.

**Comment by nemec** [comment]
Hi Mark, you need two dashes to distinguish long options from short ones. A single dash is always interpreted as a short option (equivalent to `-i "gnore"`). With the above config, you need to either do

    app.exe -i value
    app.exe --ignore value
    app.exe --ignoreDiag
    app.exe -i value --ignoreDiag

**Comment by markdwood** [comment]
Thanks. I did not realize it was considered equivalent to -i "gnore"; I would have expected with the strict option for it to have flagged it as an error.

**Comment by nemec** [comment]
Yep, it follows the Linux/Unix [getopt](https://pymotw.com/2/getopt/) style.
