### ISSUE TITLE
Mutually Exclusive set and Required parameters doesn't work right.

### ISSUE THREAD

**Issue by Eric-BSB** [gsscoder/commandline#382]
If I have 4 parameters.  Two for A, and two for B.

A are optional... but if you use the B set, then BOTH are required.

I can't do this with the 1.9x release.  If I set the B set to Required, then it fails when passing A values, since the B set are still considered required, even though they are not part of the A set.

**Comment by nemec** [comment]
Hi Eric, this is the expected behavior both in 1.9x and 2.0 - you cannot have a _required_ argument that is optional in some cases but not in others. For more complex argument validation you will have to perform some post-processing yourself.

**Comment by tpluscode** [comment]
Wouldn't it be sensible to assume that a set of required, mutually exclusive parameters mean that exactly one of them must be provided? Like below, where I'd like to accept either `-c` or `-n`. Not both. Not none

``` c#
public class Options
{
    [Option('c', Required = true, SetName = "connection")]
    public string ConnectionString { get; set; }

    [Option('n', Required = true, SetName = "connection")]
    public string ConnectionStringName { get; set; }
}
```
