### ISSUE TITLE
Default values overwrite my value in 1.9.71

### ISSUE THREAD

**Issue by MonkAlex** [gsscoder/commandline#384]
Simple config:
```
    public class Config
    {
      [Option('o', Required = true)]
      public string One { get; set; }

      [Option('t', "two", Required = false)]
      public string Two { get; set; }

      [Option('h', Required = false, DefaultValue = false)]
      public bool Three { get; set; }

      [ParserState]
      public IParserState ParserState { get; set; }
    }
```

How to use:
```
      var config = new Config() {One = "One", Three = true };
      CommandLine.Parser.Default.ParseArguments(args, config);
```

With args => `--two="two"` i lost `Three` value.
Any idea, how to load config + app args?

PS: and, `ParserState` has errors, `One` is required.

**Comment by MonkAlex** [comment]
Hmmm, its work, if i move default value to ctor:
```
      [Option('h', Required = false)]
      public bool Three { get; set; }

      public Config()
      {
        Three = false;
      }
```

**Comment by nemec** [comment]
Yes, the default value overrides the constructor at parse-time. I wrote a library to handle the chore of merging multiple "sources" of config data into one object, feel free to try it out. The example below should work with the 1.9.x branch of this library.

https://github.com/nemec/smartconf.sources/tree/master/CommandLine

**Comment by MonkAlex** [comment]
How to fix ParserState? It required filled properties.

**Comment by nemec** [comment]
Set `Required` to false if it isn't actually required. The attributes only apply to _command line parsing_, if you fill the property some other way it isn't registered.

**Comment by MonkAlex** [comment]
I load config from file, then parse args.
Property required, but i don't know, where its filled - in file or in args.

I need custom validation?

**Comment by nemec** [comment]
Unfortunately yes.
