### ISSUE TITLE
Assembly naming problems on Linux

### ISSUE THREAD

**Issue by nicolasr75** [gsscoder/commandline#386]
I just tried to run a small console application that uses commandline on a Linux machine. VS publish copies a file CommandLine.dll to the output folder, capitalized with Pascal case. When I copy all files to my Linux machine and try to execute it, I get

The system cannot fnd the file specified

File name: 'commandline, Version=2.0.275.0, Culture=neutral ....

I noticed that the problem is solved if I rename the published file to all lowercase. And it is the only assembly that has this problem in my application!

Is this an issue with the nuget package maybe?

**Comment by nemec** [comment]
.Net Core or Mono? I glanced through the nuspec and csproj in the repository and both capitalize the dll correctly. I'm wondering if maybe your csproj/project.json references section is incorrectly capitalized. I would expect it to be correct based off the [nuspec](https://github.com/gsscoder/commandline/blob/master/nuget/CommandLine.nuspec), but who knows on Windows.

**Comment by nicolasr75** [comment]
.Net Core on Linux Ubuntu ARM32 (if of any importance). I could try on a Linux x64.
My Project.json has this entry:
"CommandLineParser": "2.1.1-beta"
but I did not enter this manually but used the Nuget packet manager from VS Solution Explorer.

**Comment by nemec** [comment]
How about in your xproj file? Is there a `references` element that mentions commandline?

**Comment by nicolasr75** [comment]
No references at all in there.

**Comment by nemec** [comment]
Would you be willing to zip the whole thing (source & binaries) and send it to me so I can peek around? You can upload it to Dropbox or something or (if it's just a few hundred kb) feel free to send it to the email addr on my profile.

Core is pretty new, so I'm not too familiar yet with how the source gets turned into IL (w/ its refs)

**Comment by nicolasr75** [comment]
My project is already quite complex with multiple cross project references and a complex directory structure. I will try to create a simplified version at least without any cross project references tomorrow and send it to you. Thanks for looking into this!

**Comment by nemec** [comment]
No problem. What version of Visual Studio are you trying this in?

**Comment by nicolasr75** [comment]
That is Visual Studio 2015 Community Edition and .NET Core 1.1.0 SDK x64

**Comment by nicolasr75** [comment]
Ok, it gets more complicated :-( The problem doesn't seem to occur on a normal Linux x64. It only occurs on a Raspberry Pi with ARM processor but already with a simple Hello World. I have not tested x86 systems though. I am not sure if you really want to mess around with this and if you even have a Raspberry Pi at hand. Since ARM is not yet officially supported, we should maybe wait until next year for .Net Core 2.0 which was promised to have offical ARM support.

**Comment by nemec** [comment]
Hmm, I have a Pi but I'm not able to find instructions on how to install .Net Core. Like you mentioned, it seems to not be supported yet.

You did actually solve the problem by lowercasing the filename, right? Would you be okay with that workaround for now (maybe add it as a postbuild step in the MSBuild xproj)? Once .Net Core is officially supported on ARM, feel free to reopen this if it hasn't been fixed.
