### ISSUE TITLE
Supporting integers in hex format

### ISSUE THREAD

**Issue by matthew-humphrey** [gsscoder/commandline#391]
I have an option that takes a ulong value, and I would like to allow the user to specify that in decimal or, if including a "0x" prefix, hexidecimal. I tried to implement this by declaring the option as type string, and then in my property set implementation, doing the conversion and throwing an ArgumentException if it isn't correct. 

Unfortunately, the parser doesn't treat this as an invalid argument and display the help text. It just throws an exception.

It would be great if there was a way to communicate that there was a format/conversion/validation error to the parser - perhaps some exception type you define and that the parsing code throws.

**Comment by nemec** [comment]
I think a better idea would be to implement that within the context of custom typeconverters (#343), that way your 0x value would be directly converted to a ulong type (or other integral).

I'm going to close this one as a duplicate, but if you (or anyone else reading this) is interested in implementing the feature, submit a pull request and I'll check it out.
