### ISSUE TITLE
Can Default.ParseArguments support more than 16 verbs?

### ISSUE THREAD

**Issue by drboyer** [gsscoder/commandline#394]
I have a CLI program (C#, CommandLine v2.0.275-beta) where I've been gradually expanding the number of verbs that are available. I just ran into an issue trying to add my 17th verb.

Right now, I'm using `CommandLine.Parser.Default.ParseArguments` to parse my verb and options and run different tasks, as you'd expect. Like so (simplified to only 2 verbs):

```csharp
var errorcode = CommandLine.Parser.Default.ParseArguments<
    Verb1Options,
    Verb2Options>(args).MapResult(
        (Verb1Options) => DoVerb1Actions(opts),
        (Verb2Options) => DoVerb2Actions(opts),
        errs => 1);
```

This works fine and dandy up to 16 verbs/verb option types provided to ParseArguments. However, when I go to add a 17th, I get the error `Using the generic method 'Parser.ParseArguments<T>(IEnumerable<string>)' requires 1 type arguments`. Looking at the overloads of Default.ParseArguments, IntelliSense tells me there are 17 overloads, with almost all of them just expanding the number of verb types from `T` to `<T1, T2, T3...T16>(IEnumerable<string> args)`. So I suppose based on that, when I try to add a 17th verb type, it fails.

Is there a way to support using more than 16 verbs with this library? Perhaps there's a better way than our MapResult, which leads to a really giant code block. Let me know if you need any clarification.

**Comment by nemec** [comment]
Have you tried the [params overload](https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Parser.cs#L147)?

**Comment by drboyer** [comment]
Thanks @nemec, must've missed that. Based on the ["Latest Version" documentation](https://github.com/gsscoder/commandline/wiki/Latest-Version#verbs), I am now using the params overload for ParseArguments and I switched from using MapResult to using a variety of `WithParsed<T>()` extension methods.

The only thing I can't figure out now is how to translate getting an error code back using these WithParsed methods. Each of the methods called in the `WithParsed<T>()` lambdas returns an int. Before I was using WithParsed and was using MapResult, I basically followed the [example in the Verb section of the Latest Version documentation](https://github.com/gsscoder/commandline/wiki/Latest-Version#verbs) that returns an exit code. However, I haven't quite figured out how to do that here. It doesn't seem to return something that is an int or can be cast to an int, but perhaps I'm just doing something wrong. Relatedly, I haven't figured out what the WithParsed version of the MapResult `errs => 1` is (it does not seem to be `.WithNotParsed( errs => 1)`;

**Comment by nemec** [comment]
Since `WithParsed` is a "fluent interface" it just returns itself. You'll want to use closures to assign a local error code variable. Something like this:

    var errorCode = 0;
    result
        .WithParsed<Verb1>(errs => errorCode = 10)
        .WithParsed<Verb2>(errs => errorCode = 18);

    Console.Error.WriteLine("Your error was: " + errorCode);

Is that what you're looking for?

**Comment by drboyer** [comment]
Ah yep, that's exactly it. Makes sense.

Thanks for all your help @nemec!

**Comment by nemec** [comment]
Awesome! Glad it worked out.
