### ISSUE TITLE
Displaying help text manually when parsing is successful

### ISSUE THREAD

**Issue by tpluscode** [gsscoder/commandline#396]
Here's an outline of what I'm currently doing using two verbs:

``` c#
var parserResult = Parser.Default.ParseArguments<LocalOptions, RemoteOptions>(this.args);

return parserResult
    .MapResult(
        (LocalOptions options) => UpgradeDatabase(callingAssembly, options),
        (RemoteOptions options) => UpgradeRemote(parserResult, callingAssembly, options),
        errors => 1);
```

I added a mutually exclusive options `RemoteOptions`, where one of the is required. Because there is not automatic way to check whether either one of them is provided (see #364), I want to manually display the help text in `UpgradeRemote`. 

Unfortunately, I don't know how. I tried `HelpText.AutoBuild(parserResult)` but it throws (expects `NotParsed<T>`. I also try `HelpText.RenderUsageText(parserResult)` but it returns an empty string (because `parserResult` is `ParserResult<object>` and not `ParserResult<RemoteOptions>`?).

**Comment by nemec** [comment]
Try [this overload](https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Text/HelpText.cs#L206) of AutoBuild.

**Comment by tpluscode** [comment]
Hm, yes, this one works

**Comment by nemec** [comment]
Glad to hear it! I'm going to close this issue, but let me know if you're still having trouble.

**Comment by tpluscode** [comment]
I'm just thinking that maybe the overload I tried could also work similarly? So instead of the exception being thrown on line [#286](https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Text/HelpText.cs#L287)

``` c#
if (parserResult.Tag != ParserResultType.NotParsed)
    throw new ArgumentException("Excepting NotParsed<T> type.", "parserResult");
```

maybe it could call the other overload with default params?

``` c#
if (parserResult.Tag != ParserResultType.NotParsed)
    return AutoBuild(parserResult, ht => ht, ex => ex);
```
