### ISSUE TITLE
The demo code doesn't show how to print help or error messages.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [gsscoder/commandline#399]
This code:
https://github.com/gsscoder/commandline/blob/master/demo/ReadText.Demo/Program.cs

**Comment by SurferJeffAtGoogle** [comment]
I can't figure out how to do it.

**Comment by nemec** [comment]
Hi Jeff, are you trying to print the help "on demand" or in response to the help command/errors in parsing? It should handle the `--help` and error case automatically, but let me know if you're having trouble.

**Comment by SurferJeffAtGoogle** [comment]
It does indeed.  Thank you.
