### ISSUE TITLE
How can I replace the version command?

### ISSUE THREAD

**Issue by dmoonfire** [gsscoder/commandline#403]
I want to have a modified `version` verb. However, using the word `version` gets caught by the `PreprocessorGuards` and I can't figure out how to disable that. I still want the help processing, I just want to have more information in the version command (listing every version of IoC/DI plugins).

**Comment by nemec** [comment]
Unfortunately not at the moment. I'm going to close this as a duplicate to #351, you can subscribe to that one for any updates.
