### ISSUE TITLE
Is it possible to combine global parameters with a verb?

### ISSUE THREAD

**Issue by ivanko2000** [gsscoder/commandline#411]
It seems like a common use case, but so far I could not find any reference to it in the documentation, open/closed issues or Q&As online: say I want to use the verbs scenario (e.g. 'get' and 'post') but also need to configure 'cross-cutting concerns' like logging (-log='file-path') that is relevant for all verbs:

MyCLI post -content="Hello" -log="trace.log"

Do I need to replicate those global parameters in all verbs, use inheritance or is there a "mode" that supports a combination of e.g. a global Options and verb-specific GetOptions and PostOptions classes?

**Comment by nemec** [comment]
Hi @ivanko2000, the best way would be to use inheritance. The following works fine, for example:

```csharp
void Main()
{
	var result = Parser.Default.ParseArguments<Add, Remove>("remove -l file.txt".Split());
	result.MapResult<Add, Remove, object>(
		(Add o) => o.Dump(),
		(Remove o) => o.Dump(),
		errs => errs.Dump());
}

public abstract class CommonOptions
{
	[Option('l', "log")]
	public string LogFile { get; set; }
}

[Verb("add")]
public class Add : CommonOptions
{
}

[Verb("remove")]
public class Remove : CommonOptions
{
}
```

**Comment by ivanko2000** [comment]
Thank you! This is exactly what I was looking for.
P.S. Might want to add a one liner on the documentation page to point to this approach
