### ISSUE TITLE
The demo doesn't include verbs

### ISSUE THREAD

**Issue by lost-RD** [gsscoder/commandline#414]
Since verbs are a major drawcard feature of this project, it would be nice if your demo used them.

I'm trying my best to piece together information from all the wiki pages and even pages from all over the web and nowhere is there a good guide on how to use verbs.

This project seems great but getting it running is much harder than I thought it would be.

I really don't know where to go from here because the documentation has run out (as far as I can tell). Here is my attempt thus far: https://github.com/lost-RD/GitHubRelease

I'm sure there are things in there that are right and things that are just in the wrong place or declared wrongly.

**Comment by nemec** [comment]
Does this help? It's linked in the sidebar of the wiki. Based on your project, I think you're trying to use the 2.x API with the 1.9.x nuget package.

https://github.com/gsscoder/commandline/wiki/Verb-Commands

**Comment by lost-RD** [comment]
That page does look different to what I've been looking at. Should I be using 2.x or stick with 1.9.x?

**Comment by gsscoder** [comment]
I think everything is clear now, otherwise feel free to ask more info.

**Comment by lost-RD** [comment]
I've moved to the latest pre. Looking at the wiki for Latest-Version, this section stands out:

The above output is taken from a unit test.

```CommandLine 2.0.201-alpha
Copyright (c) 2005 - 2015 Giacomo Stelluti Scala

ERROR(S):
  Option 'badoption' is unknown.

USAGE:
Cloning quietly:
  git clone --quiet https://github.com/gsscoder/railwaysharp
Cloning without hard links:
  git clone --no-hardlinks https://github.com/gsscoder/csharpx


  --no-hardlinks    Optimize the cloning process from a repository on a local 
                    filesystem by copying files.

  -q, --quiet       Suppress summary message.

  --help            Display this help screen.

  --version         Display version information.

  URLS (pos. 0)     A list of url(s) to clone.```

I want to do something like this. Can you point me to the test that generates this output?

**Comment by lost-RD** [comment]
@gsscoder please see above

**Comment by nemec** [comment]
@lost-RD this looks like the unit test in question: https://github.com/gsscoder/commandline/blob/29823474d4cbdf5fd1532676c4ef6e0f26935f5b/tests/CommandLine.Tests/Unit/ParserTests.cs#L489

Which in turn use the following [add](https://github.com/gsscoder/commandline/blob/9ff3c90990218392358c21e536cb0f918f63edb1/tests/CommandLine.Tests/Fakes/Help_Fakes.cs#L107), [commit](https://github.com/gsscoder/commandline/blob/9ff3c90990218392358c21e536cb0f918f63edb1/tests/CommandLine.Tests/Fakes/Help_Fakes.cs#L134), and [clone](https://github.com/gsscoder/commandline/blob/9ff3c90990218392358c21e536cb0f918f63edb1/tests/CommandLine.Tests/Fakes/Help_Fakes.cs#L157) verbs.

**Comment by lost-RD** [comment]
So for anyone else who had the same issue as me, the useful demo code is in this file:

commandline\tests\CommandLine.Tests\Fakes\Help_Fakes.cs
