### ISSUE TITLE
2.1.1-beta cannot parse enums?

### ISSUE THREAD

**Issue by ChangePlaces** [gsscoder/commandline#416]
I have a simple property that is a custom enum. The parsing of it worked in the latest stable release, but moving over to Core and using 2.1.1 beta from nuget is now throwing up an error that it's missing a required arg. Some digging showed that it's case sensitive and the wrong case causes two exceptions: defined with a bad format, and option is missing.

Can enum parsing become case-insensitive please?

**Comment by nemec** [comment]
Can you post your options class and inputs? This works fine for me:

	void Main()
	{
		var result = Parser.Default.ParseArguments<Options>("-d Monday".Split());
		result.WithParsed(o => o.Dump());
		result.WithNotParsed(e => e.Dump());
	}
	
	public class Options
	{
		[Option('d', "day", Required = true)]
		public Day Day { get; set; }
	}
	
	public enum Day
	{
		Monday,
		Tuesday,
		Wednesday
	}

**Comment by ChangePlaces** [comment]
in your example, "monday" wouldn't.

**Comment by nemec** [comment]
Oh, shoot. I completely missed that part of your submission, sorry. Will check it out.

**Comment by nemec** [comment]
You need to build your own parser, configured with case insensitivity.

	var parser = new Parser(conf =>
	{
		conf.CaseInsensitiveEnumValues = true;
	});
	var result = parser.ParseArguments<Options>("-d monday".Split());

**Comment by ChangePlaces** [comment]
I think it should be case insensitive by default as enums can usually have casing which may not make sense on command line.
