### ISSUE TITLE
Having an issue with MapResult

### ISSUE THREAD

**Issue by lost-RD** [gsscoder/commandline#430]
I'm attempting to set up my Main method in the way the documentation suggests:

```C#
int Main(string[] args) {
  return Parser.Default.ParseArguments<AddOptions, CommitOptions, CloneOptions>(args)
    .MapResult(
      (AddOptions opts) => RunAddAndReturnExitCode(opts),
      (CommitOptions opts) => RunCommitAndReturnExitCode(opts),
      (CloneOptions opts) => RunCloneAndReturnExitCode(opts),
      errs => 1);
}
```

but I get an error when I try to build:

`Error	CS0411	The type arguments for method 'ParserResultExtensions.MapResult<T1, T2, T3 TResult>(ParserResult<object>, Func<T1, TResult>, Func<T2, TResult>, Func<T3, TResult>, Func<IEnumerable<Error>, TResult>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.`

**Comment by nemec** [comment]
Try `MapResult<AddOptions, CommitOptions, CloneOptions, int>(`...

**Comment by lost-RD** [comment]
Having done that, it seems that what I need to do is have all of the methods (such as RunAddAndReturnExitCode) return an int. Is this necessary?

**Comment by nemec** [comment]
Yes, you do. You're returning `MapResult` in your Main method which requires an int, so each of the branches must return ints as well.

**Comment by lost-RD** [comment]
Thanks! I got it working and am super happy with the library now.

**Comment by nemec** [comment]
Great to hear!
