### ISSUE TITLE
Make it easier to get a pre-typed options member

### ISSUE THREAD

**Issue by ptr727** [gsscoder/commandline#446]
Given that the type of the options class is known, and the value is available, make it easier to get the actual option object as a member variable of the parser class.
Having to cast to get it is non-intuitive.

```
            // Parse the commandline arguments
            // https://github.com/gsscoder/commandline
            Parser parser = new Parser(with =>
            {
                with.CaseSensitive = false;
                with.HelpWriter = Console.Error;
            });
            ParserResult<Options> result = parser.ParseArguments<Options>(args);
            if (result.Tag == ParserResultType.NotParsed)
            {
                return -1;
            }
            // TODO : Why do I need to cast to get the options?
            Options options = ((Parsed<Options>)result).Value;
```

**Comment by nemec** [comment]
Please read [the documentation](https://github.com/gsscoder/commandline/wiki/Latest-Version#parsing).

> Two convenient extension methods are provided to help you access values:
> 
>     var result = Parser.Default.ParseArguments<Options>(args)
>        .WithParsed(options => ...) // options is an instance of Options type
>        .WithNotParsed(errors => ...); // errors is a sequence of type IEnumerable<Error>

**Comment by ptr727** [comment]
I'm not fluent in C#, certainly not in Lambda expressions, classic C++ is my goto language.
It is totally not obvious from the examples how to use the options object in other expressions.
E.g. if (result.Options.SomeValue == 14 || someothervalue > 0)

May I kindly suggest you create examples that do not require the user to be fluent in => to figure out what is going on.

**Comment by nemec** [comment]
Basically, your lambda would execute your application (so you'd put all of those if statements inside the lambda).

```csharp
...
.WithParsed(options =>
{
    if(options.SomeValue == 14 || someothervalue > 0)
    {
         ScrapeWebpage(options.OtherValue);
    }
    Logger.Info("Finished with application");
}
```

**Comment by ptr727** [comment]
Thx, now I know how.
But, I'd rather static cast, this format is not conducive to help my procedural flow that just needs a couple options from the commandline.
