### ISSUE TITLE
Package CommandLineParser 1.9.71 is not compatible with netcoreapp1.1 

### ISSUE THREAD

**Issue by ibruynin** [gsscoder/commandline#454]
Hi

I'm unable to install CommandLineParser in a .net core app.

Install-Package : Package CommandLineParser 1.9.71 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package CommandLineParser 1.9.71 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)

Is it possible to support this as well?

Thanks!
Ian

**Comment by HelloKitty** [comment]
You should enable pre-release nugets to gain access to the netstandard compatible beta.

**Comment by ibruynin** [comment]
pre-release worked fine!
