### ISSUE TITLE
Add example usage to Readme

### ISSUE THREAD

**Issue by mattfrear** [gsscoder/commandline#474]
You've got examples of how to set it up in C#, F#, VB etc, but no examples of how to use it at the command line.

e.g. is it 'myprogram.exe r filename' or 'myprogram.exe -r filename' or 'myprogram.exe -r=filename' or 'myprogram.exe --r filename' etc. I have no idea.

**Comment by MikelThief** [comment]
https://github.com/gsscoder/commandline/wiki/Quickstart

it is described here. You are just not reading carefully.

**Comment by mattfrear** [comment]
OK, they are on the wiki quickstart page but they are not on the Readme which is where I was looking.

**Comment by mattfrear** [comment]
Anyway, I don't even use this package cos I couldn't find the info needed to get started. So I raised the issue to help you address it. Looks like this repo is no longer maintained so I'm closing the issue.
