### ISSUE TITLE
How to set Option with the requirement to have exact two values? 

### ISSUE THREAD

**Issue by dasdingo** [gsscoder/commandline#483]
I want to create an Option where at least two values are required but I don't find an attribute like that. Is there a way to define such a requirement? Example: --openSheet [path] [table]

**Comment by gaston-e-nusimovich** [comment]
You could use the [OptionArray] attribute in a fashion similar to the following example (see code sample below); maybe in your case you would rather use string[].

[OptionArray('v', "values", DefaultValue = new double[] {.1, .2, .3})]
  public double[] Temperatures { get; set; }

:0)

**Comment by gaston-e-nusimovich** [comment]
hmmm, after giving some more thinking time to your question, maybe the following example is a better fit to your reqs:

 [ValueList(typeof(List<string>), MaximumElements = 2)]
  public IList<string> OtherStuff { get; set; }

;0)

**Comment by nemec** [comment]
Are you using the 2.0 beta? You should be able to use the `Option("openSheet", Min=2)` syntax to set the minimum number of values.

**Comment by dasdingo** [comment]
I switched to version 2.0.0.0, but when using the Min and Max properties it seems that the validator doesnt check for the amount of values. So it is not possible for me to trigger a parse issue when having less than 3 values. Example:" --command a b"->result is still valid

[Option('c', "command", Min = 3,Max = 3, HelpText = "Command desc.")]
		public IEnumerable<string> Commands { get; set; }

**Comment by dasdingo** [comment]
I just played around with the amounts of parameter and I could see that the "Min" requirement is working, but the "Max" requirement is ignored.

**Comment by dasdingo** [comment]
I used version 2.0.0.0 before. Now I am using 2.0.275.0 and everything works fine! Thank you very much!
