### ISSUE TITLE
Question: Default verb

### ISSUE THREAD

**Issue by rwatjen** [gsscoder/commandline#490]
I have a command line tool with three verbs.
One is supposed to be used almost all the time. Is it possible to use it as default, unless one of the other verbs are specified, so e.g.
mycmd.exe --verb1optionA --verb1optionB
does the same as
mycmd.exe verb1 --verb1optionA --verb1optionB

And the user can specify verb2 or verb3 if they want to do something else?

**Comment by nemec** [comment]
Hi @rwatjen, no that is not possible today in 2.x. If you choose to use verbs and leave one out of the arguments, parsing will return a `BadVerbSelectedError`. You could pop one on the front before parsing if you notice `args[0]` begins with a `-`, but it's not a great developer experience. I like the idea, though.

**Comment by rwatjen** [comment]
Thank you @nemec for the reply. I think I'll put the default verb in like you suggest.
