### ISSUE TITLE
Option to parse option without any switch (position based)

### ISSUE THREAD

**Issue by konrad-kruczynski** [gsscoder/commandline#50]
If you look at the (for instance) man page for grep, you'll see something like:

    grep [OPTIONS] PATTERN [FILE...]

So, `[OPTIONS]` are what the library currently parse without a problem, however how to define required or optional parameters without a switch at the beginning or end (like `PATTERN` or `[FILE...]` here)? Naturally, one can preprocess the string, splice it and then pass to the library, but why not have it out of the box? :) It would be cool to define them in attributes in a way like "first", "first after options" or something similar. What do you think? Or maybe there is such an option and I missed it.

**Comment by gsscoder** [comment]
Since this can be accomplished with `[Value(Index)]` attribute of 2.0 pre-rel, are you agree to close the issue?
cc/ @konrad-kruczynski @mizipzor

**Comment by konrad-kruczynski** [comment]
Consider following scenario in which given index based option is only valid if given switch was not used. For example this is valid:

    program index_arg

and this is valid:

    program --some_switch index_arg

but this is not valid:

    program --other_switch index_arg

In other words `index_arg` can only show up if `--other_switch` is not used.

Can I achieve that now?

**Comment by gsscoder** [comment]
@konrad-kruczynski Mmm... At the moment there's still no idiomatic way of constraining options in indexed positions.
(Probably something can be done or via adding manual checks or via mixing boolean values and unbound index values; but I discourage such practices since will complicate your code and all the parsing should be accomplished by the library).

As said as now only `[Value]` can be indexed.

If I've correctly understood your request... this could be considered a feature request.

**Comment by konrad-kruczynski** [comment]
My point is that indeed only `[Value]` can be indexed, but I'd like have some of these available only if a given switch is not used. What do you think?

**Comment by mizipzor** [comment]
I tried to read through this but the more I look at it the more confused I get. Let me doublecheck, the `index_arg` can change index depending on other switches, if neither `--some_switch` nor `--other_switch` is specified it has index 0, if *only* `--some_switch` is specified it has index 1, if `--other_switch` is specified it's not valid at all? 

If all the above is correct, it sounds really complicated to me. Going back to the original example of Grep, is this really how it works?

**Comment by mateusz-holenko** [comment]
I believe it has more to do with mutually exclusive sets: `index_arg` should be allowed only when `other_switch` is not present.

**Comment by gsscoder** [comment]
Are you talking in respect of a particular index? (Sorry maybe working only on commercial products so long made me a bit stupid...) :(

`--some_switch`, `--other_switch` is a boolean option: [Option(...)] -> set to boolean target property
index_arg is value with index: [Value(..)] -> set with index = 0
RULES:
- `--some_switch` can appear before the value with index = 0
- `--other_switch` can't, only after

This is can't be done now. But remember that index of values are not the same of command line tokes. Each token is mapped on specific value after all named options are parsed.

To my opinion what you require could complicate the parser and I'd like to hear more opinions before implementing something so specific... (Hope you understand).

The other question is: how can we implement custom rules like this in a general manner? With a lambda function?

**Comment by gsscoder** [comment]
Hi @mizipzor ! How much time, Alexander...

@mateusz-holenko Hi, happy you joined discussion!

I think that @mizipzor expressed something similar my last post, isn't it?

**Comment by konrad-kruczynski** [comment]
Yeah, the point is that software can, for example, execute script (given as an indexed argument) or execute a command (with `e` option). But one cannot use both options at the same time. So this is legal:

    software.exe script_name

and this is legal:

    software.exe -e command

but this is not:

    software.exe -e command script_name

**Comment by gsscoder** [comment]
@mizipzor I think he want something the plug-in part added to latest stable by @gimmemoore ... The plug-in friendly architecture is explained [here](https://github.com/gsscoder/commandline/wiki/Plug-in-Friendly-Architecture); but it's stable only for now...

**Comment by mizipzor** [comment]
Hm, this is starting to sound similar to *subparsers* or the concept of *verbs*. I think it was discussed somewhere... or was it even a pull request? I can't find it now, though.

**Comment by gsscoder** [comment]
@mizipzor you're talking of nesting multiple verb commands? that post?

**Comment by konrad-kruczynski** [comment]
And yup, regarding method to let the user communicate complex scenarios, the simplest one would probably be to accept some validating function. Here one would only need to extend existing mutual exclusion options to indexed parameters.

**Comment by gsscoder** [comment]
@konrad-kruczynski kernel of 2.0 try to be as more functional as C# allows (at the moment of writing); so I vote up :+1: for a validating function in the concrete sense of the word.

@mizipzor ?

**Comment by mizipzor** [comment]
If you want my opinion in any official capacity I'll have to abstain from voting as I don't feel I understand the problem well enough anymore. If we can delegate validation to the implementer, sure. But I'm still struggling to see why you would want a program to behave this way, grep was the example initially but it doesn't seem to be anymore, can we try to find a command line tool that works like this?

**Comment by gsscoder** [comment]
@mizipzor Agree it's a too particular question...

But moving the discussion forward I think it could be useful allow some custom validation step using lambda functions... My :+1: was toward solving the general problem with this kind of architecture that marries with 2.0 kernel.

**Comment by gsscoder** [comment]
This is possible from 2.0.x+. So I close issue.
