### ISSUE TITLE
CultureAttribute for interpreting culture specific input

### ISSUE THREAD

**Issue by isolaol** [gsscoder/commandline#53]
Dear gsscoder,

Command line parser uses the culture setting of the hosting process to interpret input and set property values of option class. The data feed from command line might not match the culture of the process hosting parser. In the worst case, the hosting process doesn't know which culture is used to format the input it is interpreting. It means that the hosting process cannot adapt to input culture by altering Thread.CurrentThread.CurrentCulture before calling CommandLine.CommandLineParser.ParseArguments.

So, I propose a special CultureAttribute to be implemented. The idea is that programmer can decorate one property of the option class with CultureAttribute. The parser should interpret input with culture specified via command line. An example of option class property with a new CultureAttribute attribute:

```csharp
[Culture('c', "culture", MetaValue = "NAME", DefaultValue = "en-US", HelpText = "Specify which culture NAME is used to interpret command line options.")]
public System.Globalization.CultureInfo Culture { get; set; }
```

As a result, app.exe can be called with input formatted in multiple ways:

app.exe --culture en-US --value 1023.45
app.exe --culture fi-FI --value "1 234,45"

I suggest that CultureAttribute attribute should understand culture names known by CreateSpecificCulture method of CultureInfo class. For more information, look at:

http://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.createspecificculture.aspx

Parser should change Thread.CurrentThread.CurrentCulture if CultureAttribute attribute has Permanent property (defaults to false) switched on. Otherwise, culture setting should affect input parsing only.

This is my weak attempt to describe what CultureAttribute might look like:

```csharp
/// <summary>
/// Models an culture specification.
/// </summary>
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
public sealed class CultureAttribute : BaseOptionAttribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="CommandLine.CultureAttribute"/> class.
    /// </summary>
    /// <param name="shortName">The short name of the culture option..</param>
    public CultureAttribute(char shortName)
        : base(shortName, null)
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="CommandLine.CultureAttribute"/> class.
    /// </summary>
    /// <param name="longName">The long name of the culture option.</param>
    public CultureAttribute(string longName)
        : base(null, longName)
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="CommandLine.CultureAttribute"/> class.
    /// </summary>
    /// <param name="shortName">The short name of the culture option.</param>
    /// <param name="longName">The long name of the culture option or null if not used.</param>
    public CultureAttribute(char shortName, string longName)
        : base(shortName, longName)
    {
    }

    /// <summary>
    /// Gets or sets the persistence mode of the culture setting.
    /// </summary>
    public bool Permanent { get; set; }

    /// <summary>
    /// Helper factory method for testing purpose.
    /// </summary>
    internal OptionInfo CreateOptionInfo()
    {
        return new OptionInfo(base.ShortName, base.LongName);
    }
}
```

Thanks for your devotion to this library. It has helped me a lot!

Kind regards,
Olli-Pekka Isola

**Comment by gsscoder** [comment]
I think that pre-rel 2.0 learnt the lesson... Or am I wrong?

If I'm right, can the issue be closed?

cc/ @isolaol

**Comment by mizipzor** [comment]
Considering the lack of activity, it's time to close this (just reopen if need be).
