### ISSUE TITLE
Proper formatting in HelpText of options with DefaultValue set to arrays.

### ISSUE THREAD

**Issue by gsscoder** [gsscoder/commandline#65]
Created from
http://stackoverflow.com/questions/15208931/default-values-for-lists-arrays-using-command-line-parser-library
by @pheiberg.

@pheiberg, thank you for taking time to report issue. As the previous, will be fixed ASAP.

Regards, Giacomo

**Comment by gaborigloi** [comment]
This issue seems to be present in the latest (git) version. I'm still getting `(Default: System.String[])`.

**Comment by gsscoder** [comment]
This is an issue, I've to put my mind on it again ... :smile:

Did the problem persists with actual 2.0.* version?

**Comment by gaborigloi** [comment]
@gsscoder yeah, I've just pulled from this git repo

**Comment by gaborigloi** [comment]
Would it be a good idea to use `OptionAttribute.Separator` to display the default value for lists/arrays,
e.g. `Default: a;b` for 
```[Option('w', Separator = ';', Default = new [] {"a", "b"})]
public IEnumerable<string> Words { get; set; }```
That would serve as an example and correspond directly to the expected input format.

**Comment by gaborigloi** [comment]
Sorry I just realised that space-separated lists are always accepted.

**Comment by gsscoder** [comment]
@gaborigloi, anyway you were right! This issue was re-introduced with 2.0.x version.

Why? Because kernel was heavily refactored and same change to satellite types may have lost due to different internal software structure.

Now this is fixed also for 2.0 (I'm talking of `Default` output problem, yes in 2.0 is called `Default` not `DefaultValue`).

Am I right or do you have spotted something new? If yes, please tell me...

Thanks again! :)

**Comment by gsscoder** [comment]
**2.0.223-beta** fixes it (just commited!) and also on **NuGet**.
![commandlineparser-2 0 223-beta_on_nuget-screenshot](https://cloud.githubusercontent.com/assets/1194228/9041233/44101c30-3a07-11e5-88f8-9e779e52cd20.png)
Can you check if everything work and tell me if not (please)?

**Comment by gsscoder** [comment]
I've also added two comments in S.O. topic: http://stackoverflow.com/questions/15208931/default-values-for-lists-arrays-using-command-line-parser-library.

**Comment by gaborigloi** [comment]
@gsscoder I've just checked 2.0.223.0 and it works fine :)
no problem, and thanks for the fix :)

**Comment by gsscoder** [comment]
Perfect @gaborigloi, thanks for checking it and using this library.

And for everything, don't hesitate and back here, I or one of your excellent contributors will try to assist!
