### ISSUE TITLE
Possibility to make an "option group" where the user has to use exactly one of the options in the group

### ISSUE THREAD

**Issue by pheiberg** [gsscoder/commandline#66]
When creating an application that has a group of options of which one must be given and only one of them can be given at a time, there is currently no way to do that. `MutuallyExclusiveSet` and `Required` can't be used together.

Example: I have an application where the user either can process files using
    `MyApp --files myfile.txt`
or get a list of possible languages to use to process the files
    `MyApp --list-languages`
or get a list of available plugins
    `MyApp --list-plugins`
etc

Using more than one option or none of them would render an error.

A verb based approach could solve it, but seems wrong since the applications only real command is to process files and the rest of the command would just be some sort of help commands.

The [Plossum Command Line Parser](http://www.codeproject.com/Articles/19869/Powerful-and-simple-command-line-parsing-in-C) is using the notion of [OptionGroup](http://www.codeproject.com/Articles/19869/Powerful-and-simple-command-line-parsing-in-C#x1-150004.1.2)s, where a group can have a setting of:  
>* None 
>   This is the default, and it means that no restrictions are placed on the options in this group (other than those explicitly specified for each option)
>* AtMostOne 
>    This indicates that at most one of the options contained within this group must be specified. It means that either none of the options in the group, or one of the options in the group may be specified, but no more.
>* AtLeastOne 
>    This indicates that at least one of the options contained within this group must be specified, i.e. one or more options from this group must be specified.
>* ExactlyOne 
>    This indicates that exactly one option from this group must be specified, no more and no less.
>* All 
>    Indicates that all options from this group must be specified on the command line.

This would be a good way to solve it IMO.

Another alternative I can think of - off the top of my head - would be to allow `MutuallyExclusiveSet` and `Required` to be combined. An option with `Required` would then cause it's `MutuallyExclusiveSet` to be required instead of the option.

A stackoverflow question on this issue is posted [here](http://stackoverflow.com/q/15208798/66849).

**Comment by gsscoder** [comment]
@pheiberg  Check PRs this should be solved as now.

If you're satisfied, please let me if I can close this issue.

Thanks.

**Comment by mizipzor** [comment]
Considering the lack of activity, it's time to close this (just reopen if need be).
