### ISSUE TITLE
empty OptionList doesn't show error

### ISSUE THREAD

**Issue by turch** [gsscoder/commandline#68]
I just started using this library, so forgive me if this is stupid request:

When an empty option list is parsed, shouldn't a format error be added to the PostParsingState? As I'm sure you know, It would be a one line change to add

```
DefineOptionThatViolatesFormat(option);
```

to the block that tests whether the option is empty. (OptionGroupParser.cs L54)

e.g.
```
class Options
{
   [OptionList('d', "date-range", Separator = ':')]
   public List<string> DateRange { get; set; }
}
```

```
>foo.exe -d

   -d/--date-range option violates format

>

**Comment by gsscoder** [comment]
New 2.0 pre-rel automatically handle collection targets using always `[Option]` attribute. I'm going to check if there's unit test coverage for this, if not I'll add one.

**Comment by gsscoder** [comment]
Sorry, please not take into account last post...

This feature lacks in 2.0 pre-rel, it will be implemented ASAP.

So I mark the issue as enhancement in respect of master branch.

**Comment by gsscoder** [comment]
I'm experimenting on issue68 branch (derived from master and still work in progress) how to implement previous `OptionList` adding only a `Separator` property to the model (both Option and Value attrs).

When targeting `IEnumerable<T>` two things could happens:
- the single argument is expanded after being divided by Separator and everything proceeds as with normal sequence parsing
- or we can treat it as particular conversion in which the value is processed by `string.Split(...)`

cc/ @turch @nemec 

Some reasoning is necessary... I want to keep the core of 2.0 as compact as possible.

**Comment by nemec** [comment]
In the master branch, it seems like there is no way to explicitly say you want to parse multiple parameters, right? That knowledge is gained from a combination of `OptionAttribute` + `IEnumerable<T>` type.

So let's say, without any additional configuration would you allow this as a valid input?

    [Option('i')]
    public IEnumerable<int> Integers { get; set; }

-

    $ example.exe -i 1 2 3 4

If so, it may be more "clean" to do your first suggestion of splitting `-i 1:2:3:4` into a sequence of arguments `-i 1 2 3 4` and continuing with normal parsing. However, adding a separator might create duplicate functionality (with the separator vs. with spaces) and allow some weird situations:

    $ example.exe -i 1:2:3 4 5 6:7 8

I'd be inclined to say that whitespace is always the separator and if you want something custom you could apply a custom TypeConverter to the property (which will allow the user to perform any custom conversion)

**Comment by gsscoder** [comment]
@nemec, yes you'll right. As now is impossible in 2.0...! I've started something (still not completed -> in a branche named **issue68**.
- DONE: I've added a Separator property to public attributes and specification model types.
- TODO: "cheat" the parser when Separator has a value != "" (or it can be redefined `Maybe<string>` just in the model), split the arg and explode it in the token sequence.

Thanks for comments.

**Comment by gsscoder** [comment]
I'm about to merge issue68 -> master... I've temporary added Separator to both Option and Value, but I think that only Option should have it (so it's consistent with latest stable).

I'll revert back this thing for Value attr, add few test and merge to master.

cc/ @nemec @mizipzor @gimmemoore

**Comment by gsscoder** [comment]
```csharp
[Option('i', Separator=":")]
public IEnumerable<int> Integers { get; set; }
```

This is now possible... Is the old `OptionList`. I close the issue. I'm wondering if it's better define the Separator as `System.Char`.
