### ISSUE TITLE
'LongName' is not a valid named attribute argument.

### ISSUE THREAD

**Issue by SpaghettiMonster** [gsscoder/commandline#85]
When attempting to create an option attribute, if you add LongName="foo" to the named parameters, you get the following compile-time error:

'LongName' is not a valid named attribute argument. Named attribute arguments must be fields which are not readonly, static, or const, or read-write properties which are public and not static.

Worked around it by using the constructor version that takes LongName as a parameter, but I think this is a bug.

Also, the documentation indicates that if LongName is omitted, it will be inferred from the property name. This does not appear to be a true statement. When I omit LongName, the help text is generated with no names at all, just descriptions.

**Comment by Litee** [comment]
@ericnewton76 Are you sure that your sample works OK with exact cased parameter name?

**Comment by Litee** [comment]
@cosmo0 I am not sure that your unit test is correct - you are trying to use long name for parameter that defines short name only. From code it looks like long name is inferred only if neither short nor long name are provided explicitly.

**Comment by gsscoder** [comment]
First of all, I recommend to specify the version referenced in your posts; also if here is clear that we're talking about 2.0 pre-rel.

@nemec as long time user and one of first main contributors know both CommandLine code bases very well and he's right. No way, `LongName` is internal and @SpaghettiMonster you should use the constructor.

In 2.0 this thought for let users define in a simple way (with less typing) their command line attributes. As @ericnewton76 says, omitting all names -> generates a lowercased long name.

@cosmo0, I've not check you test but I'm pretty sure this work as expected... Can you check again with latest 2.0 codebase status? If not I'll be glad to accept a PR with test (or with test and fix).

Please let me know if this issue can be closed?

cc/ @nemec @ericnewton76  @cosmo0, @Litee, @mizipzor, @gimmemoore

**Comment by gsscoder** [comment]
Given this options type:
```csharp
class FakeOptions {
  [Option(HelpText = "Define a string value here.")]
  public string StringValue { get; set; }
  // ...
}
```
and thos test theory:
```csharp
[Theory]
[InlineData(new[] {"--stringvalue", "this-value"}, "this-value")]
[InlineData(new[] {"--stringvalue=this-other"}, "this-other")]
public void Omitting_names_assumes_identifier_as_long_name(string[] arguments, string expected) {
  var result = InstanceBuilder.Build(() => new FakeOptions(), arguments, StringComparer.Ordinal,
    CultureInfo.InvariantCulture);

  Assert.True(expected.Equals(result.Value.StringValue));
}
```
I think I can close the issue. If there's other to say, feel free to re-open or add comments.
