### ISSUE TITLE
Result is wrong if there are two same values

### ISSUE THREAD

**Issue by GuanweiLi** [gsscoder/commandline#86]
My Option class is 

        [Option('s', "EnableSorting", Required = false, HelpText = "Whether enable sorting simulator", DefaultValue = false)]
        public bool EnableSorting { get; set; }

        [Option('g', "GBDeviceAddress", Required = false, HelpText = "Address of gb device", DefaultValue = "127.0.0.1")]
        public string GBDeviceAddress { get; set; }

        [Option('l', "LocalAddressToGB", Required = false, HelpText = "Local address to GB", DefaultValue = "127.0.0.1")]
        public string LocalAddressToGB { get; set; }

        [Option('m', "SharedMemorySize", Required = false, HelpText = "Shared memory size", DefaultValue = 20971520)]
        public int SharedMemorySize { get; set; }

        [Option('c', "SharedMemoryPoolCapacity", Required = false, HelpText = "Shared memory pool capacity", DefaultValue = 10)]
        public int SharedMemoryPoolCapacity { get; set; }

        [Option('p', "GBSendPacketCount", Required = false, HelpText = "GB send packet count", DefaultValue = "1.0M")]
        public string GBSendPacketCount { get; set; }

When i use command 
--GBDeviceAddress="10.10.11.78" --LocalAddressToGB="10.10.11.79"
Both values are set correctly.
But when i use command (the values are same)
--GBDeviceAddress="10.10.11.78" --LocalAddressToGB="10.10.11.78"
The LocalAddressToGB is always the default value.

**Comment by gsscoder** [comment]
https://github.com/gsscoder/commandline/pull/87 merged
