### ISSUE TITLE
2.0 beta master could not be compiled for .net 3.5

### ISSUE THREAD

**Issue by kirillkovalenko** [gsscoder/commandline#89]
The readme states that version 2.0 requires 3.5+. But it seems to be false, as the code uses Tuple<T> and Lazy<T> and therefore could not be compiled for 3.5 per se. 

I'm not sure if this is intentionally and readme is just out of date or it's due to using 4.0 as default target. Please clarify the status.

**Comment by gsscoder** [comment]
The confusion may arise because of stable and pre-release differences. The statement is true for stable, but not for 2.0 (I'll update the README) since 2.0 use more advanced language constructs.

Thanks for pointing out.
