### ISSUE TITLE
IEnumerable<string> is not parsed correctly causing parser errors.

### ISSUE THREAD

**Issue by attilah** [gsscoder/commandline#94]
I've a verb based option which has a string list option, and it fails to parse.

 

Here is the options class:
 

```
[Verb("foo", HelpText = "...")]
 public class FooSubOptions
 {
     [Option('c', "cc", HelpText = "...", Required = true)]
     public IEnumerable<string> C { get; set; }

    [Option('t', "tt", HelpText = "...", Required = true)]
     public bool T { get; set; }
```

 Here is how I parse (taken from your tests)

 
```
var writer = new StringWriter();
 var parser = new Parser(with =>
 {
     with.HelpWriter = writer;
     with.CaseSensitive = false;
     with.IgnoreUnknownArguments = false;
     with.ParsingCulture = CultureInfo.InvariantCulture;
 });

var result = parser.ParseArguments <FooSubOptions>(args);
```

I tried to compare my options class with the one you're using to parse a list of integers, and beside the data type I found no difference, Option specs are matching.

 

I found out that something goes wrong during the partitioning in InstanceBuilder, since the returned partitions are a "mess" and that's causing the missing option output in the help writer.

It seems that's it a missing test case.

 

If I changed the type of IntSequence to string in FakeOptions then I was able to repro the same error with your test.

**Comment by gsscoder** [comment]
If this is about 2.0, parser had problem in matching named sequence options with values when omitting Mix/Max constraint.
This SHOULD be fixed with Issue #157.

But there's could be a problem when using Min without Max.

I close this issue and eventually open an appropriate one.

@nemec, if I'm wrong, please re-open.
