### ISSUE TITLE
Info on parse failure

### ISSUE THREAD

**Issue by ekkis** [gsscoder/commandline#99]
I'm running ParseArgumentsStrict and when it fails my program immediate exits, displaying the syntax but gives me no clue as to why it failed.  where do I look?

**Comment by gsscoder** [comment]
@coyot, from months everything is update. Check it out!

@ekkis, when parsing fails you got a `NotParsed<T>` instead of `Parsed<T>`.

It' documented here: https://github.com/gsscoder/commandline/wiki/Latest-Version.

Thanks to both for using the library.
